onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
overrides:
  multer@>=1.4.4-lts.1 <2.0.0: '>=2.0.0'
  multer@>=1.4.4-lts.1 <2.0.1: '>=2.0.1'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  multer@>=1.4.4-lts.1 <2.0.2: '>=2.0.2'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
