import { Product } from 'src/types/Product';

export const ceramics: Product[] = [
  {
    id: 1,
    name: 'Handcrafted Vase',
    slug: 'Handcrafted-Vase',
    brand: 'ArtisanCraft',
    productImage:'Ceramics/ceramicOne.webp',
    productTitle: 'Elegant Handcrafted Ceramic Vase',
    productPrice: 45.99,
    category: 'ceramics',
    material: 'Ceramic',
    isAvailable: true,
    stock: 20,
    ratings: 4.7,
    tags: ['vase', 'handcrafted', 'decor'],
    colors: ['Blue', 'White'],
    shipping: {
      weight: 1.2,
      dimensions: {
        width: 0.15,
        height: 0.3,
        depth: 0.15,
      },
    },
    productDescription: {
      main: 'A beautiful vase handcrafted by local artisans.',
      descOne: 'Perfect for displaying fresh flowers.',
      descTwo: 'Made from sustainable materials.',
      descThree: 'Adds a touch of elegance to any room.',
    },
    productDimensions: {
      height: '30.48 cm',
      weight: '1.13 kg',
      depth: '11.43 cm',
    },
  },
  {
    id: 2,
    name: 'Decorative Bowl',
    slug: 'Decorative-Bowl',
    brand: 'RusticCharm',
    productImage:'Ceramics/ceramicTwo.webp',
    productTitle: 'Rustic Decorative Ceramic Bowl',
    productPrice: 35.5,
    category: 'ceramics',
    material: 'Ceramic',
    isAvailable: true,
    stock: 15,
    ratings: 4.5,
    tags: ['bowl', 'decorative', 'rustic'],
    colors: ['Brown', 'Green'],
    shipping: {
      weight: 0.9,
      dimensions: {
        width: 0.2,
        height: 0.1,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'A versatile bowl with a rustic charm.',
      descOne: 'Hand-painted with intricate designs.',
      descTwo: 'Ideal for holding fruit or as a centerpiece.',
      descThree: 'Durable and chip-resistant.',
    },
    productDimensions: {
      height: '10.16 cm',
      weight: '0.82 kg',
      depth: '20.32 cm',
    },
  },
  {
    id: 3,
    name: 'Ceramic Mug Set',
    slug: 'Ceramic-Mug-Set',
    brand: 'EverydayEssentials',
    productImage:'Ceramics/ceramicThree.webp',
    productTitle: 'Minimalist Ceramic Mug Set',
    productPrice: 25.0,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 30,
    ratings: 4.6,
    tags: ['mugs', 'minimalist', 'set'],
    colors: ['Gray', 'Black', 'White'],
    shipping: {
      weight: 1.4,
      dimensions: {
        width: 0.1,
        height: 0.09,
        depth: 0.07,
      },
    },
    productDescription: {
      main: 'Set of 4 minimalist mugs perfect for daily use.',
      descOne: 'Microwave and dishwasher safe.',
      descTwo: 'Smooth matte finish for a modern look.',
      descThree: 'Available in various colors.',
    },
    productDimensions: {
      height: '8.89 cm',
      weight: '0.36 kg per mug',
      depth: '7.62 cm',
    },
  },
  {
    id: 4,
    name: 'Ceramic Planter',
    slug: 'Ceramic-Planter',
    brand: 'GreenThumb',
    productImage:'Ceramics/ceramicFourth.webp',
    productTitle: 'Contemporary Ceramic Planter',
    productPrice: 29.99,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 18,
    ratings: 4.8,
    tags: ['planter', 'ceramic', 'modern'],
    colors: ['Terracotta', 'White'],
    shipping: {
      weight: 0.6,
      dimensions: {
        width: 0.14,
        height: 0.15,
        depth: 0.14,
      },
    },
    productDescription: {
      main: 'A sleek planter perfect for indoor plants.',
      descOne: 'Features a drainage hole for healthy roots.',
      descTwo: 'Glazed for a smooth finish.',
      descThree: 'Suitable for small to medium-sized plants.',
    },
    productDimensions: {
      height: '15.24 cm',
      weight: '0.54 kg',
      depth: '13.97 cm',
    },
  },
  {
    id: 5,
    name: 'Serving Platter',
    slug: 'Serving-Platter',
    brand: 'DiningDelight',
    productTitle: 'Large Ceramic Serving Platter',
    productImage:'Ceramics/ceramicFive.webp',
    productPrice: 50.75,
    category: 'ceramics',
    material: 'Earthenware',
    isAvailable: true,
    stock: 12,
    ratings: 4.9,
    tags: ['platter', 'ceramic', 'serving'],
    colors: ['Blue', 'Cream'],
    shipping: {
      weight: 1.7,
      dimensions: {
        width: 0.4,
        height: 0.03,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'A statement piece for serving guests.',
      descOne: 'Perfect for appetizers or desserts.',
      descTwo: 'Elegant hand-painted design.',
      descThree: 'Durable and easy to clean.',
    },
    productDimensions: {
      height: '2.54 cm',
      weight: '1.59 kg',
      depth: '38.1 cm',
    },
  },
  {
    id: 6,
    name: 'Modern Ceramic Pitcher',
    slug: 'Modern-Ceramic-Pitcher',
    brand: 'PurePour',
    productImage:'Ceramics/ceramicSix.webp',
    productTitle: 'Elegant Ceramic Water Pitcher',
    productPrice: 40.99,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 20,
    ratings: 4.6,
    tags: ['pitcher', 'modern', 'ceramic'],
    colors: ['White', 'Gray'],
    shipping: {
      weight: 1.5,
      dimensions: {
        width: 0.1,
        height: 0.25,
        depth: 0.1,
      },
    },
    productDescription: {
      main: 'A sleek and modern ceramic pitcher perfect for daily use.',
      descOne: 'Large capacity with an ergonomic handle.',
      descTwo: 'Perfect for serving water, juices, and more.',
      descThree: 'Smooth matte finish in white.',
    },
    productDimensions: {
      height: '25.4 cm',
      weight: '1.5 kg',
      depth: '10.16 cm',
    },
  },
  {
    id: 7,
    name: 'Hand-Painted Ceramic Plate',
    slug: 'Hand-Painted-Ceramic-Plate',
    brand: 'ArtPlate',
    productImage:'Ceramics/ceramicSeven.webp',
    productTitle: 'Artistic Hand-Painted Ceramic Plate',
    productPrice: 28.25,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 15,
    ratings: 4.8,
    tags: ['plate', 'hand-painted', 'art'],
    colors: ['Multicolor'],
    shipping: {
      weight: 0.8,
      dimensions: {
        width: 0.25,
        height: 0.03,
        depth: 0.25,
      },
    },
    productDescription: {
      main: 'A unique hand-painted ceramic plate.',
      descOne: 'Features vibrant floral designs.',
      descTwo: 'Ideal for serving appetizers or desserts.',
      descThree: 'Microwave and dishwasher safe.',
    },
    productDimensions: {
      height: '2.54 cm',
      weight: '0.72 kg',
      depth: '25.4 cm',
    },
  },
  {
    id: 8,
    name: 'Ceramic Candle Holder',
    slug: 'Ceramic-Candle-Holder',
    brand: 'GlowCraft',
    productImage:'Ceramics/ceramicEight.webp',
    productTitle: 'Minimalist Ceramic Candle Holder',
    productPrice: 19.99,
    category: 'ceramics',
    material: 'Clay',
    isAvailable: true,
    stock: 25,
    ratings: 4.3,
    tags: ['candle holder', 'ceramic', 'minimalist'],
    colors: ['White', 'Black'],
    shipping: {
      weight: 0.5,
      dimensions: {
        width: 0.09,
        height: 0.12,
        depth: 0.09,
      },
    },
    productDescription: {
      main: 'A modern ceramic holder for pillar candles.',
      descOne: 'Crafted with a simple and elegant design.',
      descTwo: 'Durable and heat-resistant.',
      descThree: 'Available in multiple colors.',
    },
    productDimensions: {
      height: '12.7 cm',
      weight: '0.45 kg',
      depth: '8.89 cm',
    },
  },
  {
    id: 9,
    name: 'Decorative Ceramic Coasters',
    slug: 'Decorative-Ceramic-Coasters',
    brand: 'TableGuard',
    productImage:'Ceramics/ceramicNine.webp',
    productTitle: 'Set of 6 Ceramic Coasters',
    productPrice: 22.5,
    category: 'ceramics',
    material: 'Ceramic',
    isAvailable: true,
    stock: 40,
    ratings: 4.7,
    tags: ['coasters', 'decorative', 'set'],
    colors: ['Blue', 'White'],
    shipping: {
      weight: 0.4,
      dimensions: {
        width: 0.1,
        height: 0.01,
        depth: 0.1,
      },
    },
    productDescription: {
      main: 'Protect your surfaces with these decorative coasters.',
      descOne: 'Hand-painted with geometric designs.',
      descTwo: 'Durable and scratch-resistant.',
      descThree: 'Perfect for home or office use.',
    },
    productDimensions: {
      height: '1.27 cm',
      weight: '0.36 kg',
      depth: '10.16 cm',
    },
  },
  {
    id: 10,
    name: 'Ceramic Soup Bowl',
    slug: 'Ceramic-Soup-Bowl',
    brand: 'RusticTable',
    productImage:'Ceramics/ceramicTen.webp',
    productTitle: 'Rustic Ceramic Soup Bowl',
    productPrice: 18.99,
    category: 'ceramics',
    material: 'Clay',
    isAvailable: true,
    stock: 18,
    ratings: 4.5,
    tags: ['soup bowl', 'rustic', 'ceramic'],
    colors: ['Brown', 'Green'],
    shipping: {
      weight: 0.7,
      dimensions: {
        width: 0.15,
        height: 0.08,
        depth: 0.15,
      },
    },
    productDescription: {
      main: 'A durable ceramic bowl perfect for soups and stews.',
      descOne: 'Microwave and oven safe.',
      descTwo: 'Smooth interior and rustic exterior.',
      descThree: 'Available in a variety of earthy tones.',
    },
    productDimensions: {
      height: '7.62 cm',
      weight: '0.68 kg',
      depth: '15.24 cm',
    },
  },
  {
    id: 11,
    name: 'Handmade Ceramic Teapot',
    slug: 'Handmade-Ceramic-Teapot',
    brand: 'TeaTradition',
    productImage:'Ceramics/ceramicEleven.webp',
    productTitle: 'Traditional Handmade Ceramic Teapot',
    productPrice: 65.0,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 10,
    ratings: 4.9,
    tags: ['teapot', 'handmade', 'ceramic'],
    colors: ['White', 'Blue'],
    shipping: {
      weight: 1.0,
      dimensions: {
        width: 0.2,
        height: 0.18,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'A handcrafted teapot made with traditional techniques.',
      descOne: 'Perfect for brewing and serving tea.',
      descTwo: 'Glazed for a smooth finish.',
      descThree: 'Available in classic white and blue designs.',
    },
    productDimensions: {
      height: '17.78 cm',
      weight: '0.9 kg',
      depth: '20.32 cm',
    },
  },
  {
    id: 12,
    name: 'Ceramic Coffee Set',
    slug: 'Ceramic-Coffee-Set',
    brand: 'JavaHome',
    productImage:'Ceramics/ceramicTwelve.webp',
    productTitle: 'Contemporary Ceramic Coffee Set',
    productPrice: 50.0,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 16,
    ratings: 4.8,
    tags: ['coffee set', 'contemporary', 'ceramic'],
    colors: ['Matte Black', 'Gray'],
    shipping: {
      weight: 2.7,
      dimensions: {
        width: 0.15,
        height: 0.25,
        depth: 0.18,
      },
    },
    productDescription: {
      main: 'A modern coffee set including 4 cups and a carafe.',
      descOne: 'Matte finish with a sleek design.',
      descTwo: 'Dishwasher safe and heat-resistant.',
      descThree: 'Perfect for everyday use or special occasions.',
    },
    productDimensions: {
      height: '25.4 cm',
      weight: '2.5 kg',
      depth: '18.29 cm',
    },
  },
  {
    id: 13,
    name: 'Ceramic Egg Holder',
    slug: 'Ceramic-Egg-Holder',
    brand: 'FarmhouseFinds',
    productImage:'Ceramics/ceramicThirteen.webp',
    productTitle: 'Stylish Ceramic Egg Holder',
    productPrice: 12.75,
    category: 'ceramics',
    material: 'Ceramic',
    isAvailable: true,
    stock: 35,
    ratings: 4.4,
    tags: ['egg holder', 'kitchen', 'ceramic'],
    colors: ['White', 'Beige'],
    shipping: {
      weight: 0.4,
      dimensions: {
        width: 0.2,
        height: 0.04,
        depth: 0.1,
      },
    },
    productDescription: {
      main: 'An elegant ceramic holder for eggs.',
      descOne: 'Perfect for kitchen organization.',
      descTwo: 'Holds up to 12 eggs.',
      descThree: 'Available in multiple colors.',
    },
    productDimensions: {
      height: '3.81 cm',
      weight: '0.3 kg',
      depth: '20.32 cm',
    },
  },
  {
    id: 14,
    name: 'Ceramic Utensil Holder',
    slug: 'Ceramic-Utensil-Holder',
    brand: 'KitchenEssentials',
    productImage:'Ceramics/ceramicFourteen.webp',
    productTitle: 'Elegant Ceramic Utensil Holder',
    productPrice: 25.99,
    category: 'ceramics',
    material: 'Clay',
    isAvailable: true,
    stock: 22,
    ratings: 4.7,
    tags: ['utensil holder', 'kitchen', 'ceramic'],
    colors: ['Blue', 'Gray'],
    shipping: {
      weight: 0.8,
      dimensions: {
        width: 0.13,
        height: 0.15,
        depth: 0.13,
      },
    },
    productDescription: {
      main: 'Keep your kitchen utensils organized in style.',
      descOne: 'Durable and sturdy design.',
      descTwo: 'Available in multiple color options.',
      descThree: 'Dishwasher safe.',
    },
    productDimensions: {
      height: '15.24 cm',
      weight: '0.78 kg',
      depth: '12.7 cm',
    },
  },
  {
    id: 15,
    name: 'Ceramic Napkin Holder',
    slug: 'Ceramic-Napkin-Holder',
    brand: 'TableCharm',
    productImage:'Ceramics/ceramicFifteen.webp',
    productTitle: 'Decorative Ceramic Napkin Holder',
    productPrice: 17.25,
    category: 'ceramics',
    material: 'Earthenware',
    isAvailable: true,
    stock: 40,
    ratings: 4.2,
    tags: ['napkin holder', 'decor', 'ceramic'],
    colors: ['White', 'Black'],
    shipping: {
      weight: 0.5,
      dimensions: {
        width: 0.1,
        height: 0.09,
        depth: 0.1,
      },
    },
    productDescription: {
      main: 'A chic and functional napkin holder.',
      descOne: 'Crafted with a modern design.',
      descTwo: 'Suitable for dining or kitchen use.',
      descThree: 'Easy to clean and durable.',
    },
    productDimensions: {
      height: '8.89 cm',
      weight: '0.36 kg',
      depth: '10.16 cm',
    },
  },
  {
    id: 16,
    name: 'Ceramic Butter Dish',
    slug: 'Ceramic-Butter-Dish',
    brand: 'RusticSpread',
    productImage:'Ceramics/ceramicSixteen.webp',
    productTitle: 'Modern Ceramic Butter Dish',
    productPrice: 14.5,
    category: 'ceramics',
    material: 'Ceramic',
    isAvailable: true,
    stock: 12,
    ratings: 4.5,
    tags: ['butter dish', 'kitchen', 'ceramic'],
    colors: ['White', 'Natural'],
    shipping: {
      weight: 0.3,
      dimensions: {
        width: 0.1,
        height: 0.06,
        depth: 0.07,
      },
    },
    productDescription: {
      main: 'A minimalist butter dish to keep butter fresh.',
      descOne: 'Comes with a wooden lid.',
      descTwo: 'Dishwasher safe and easy to store.',
      descThree: 'Ideal for daily use.',
    },
    productDimensions: {
      height: '6.35 cm',
      weight: '0.25 kg',
      depth: '10.16 cm',
    },
  },
  {
    id: 17,
    name: 'Ceramic Storage Jar',
    slug: 'Ceramic-Storage-Jar',
    brand: 'HarvestStorage',
    productImage:'Ceramics/ceramicSeventeen.webp',
    productTitle: 'Rustic Ceramic Storage Jar',
    productPrice: 30.75,
    category: 'ceramics',
    material: 'Clay',
    isAvailable: true,
    stock: 20,
    ratings: 4.6,
    tags: ['storage jar', 'rustic', 'ceramic'],
    colors: ['Terracotta', 'Gray'],
    shipping: {
      weight: 1.2,
      dimensions: {
        width: 0.15,
        height: 0.22,
        depth: 0.15,
      },
    },
    productDescription: {
      main: 'A large ceramic jar for storing dry goods.',
      descOne: 'Features a tight-sealing wooden lid.',
      descTwo: 'Ideal for storing coffee, sugar, or flour.',
      descThree: 'Available in multiple sizes.',
    },
    productDimensions: {
      height: '20.32 cm',
      weight: '1.02 kg',
      depth: '12.7 cm',
    },
  },
  {
    id: 18,
    name: 'Ceramic Jewelry Dish',
    slug: 'Ceramic-Jewelry-Dish',
    brand: 'JewelsNest',
    productImage:'Ceramics/ceramicEighteen.webp',
    productTitle: 'Elegant Ceramic Jewelry Dish',
    productPrice: 18.99,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 25,
    ratings: 4.3,
    tags: ['jewelry dish', 'ceramic', 'decor'],
    colors: ['Ivory', 'Pink'],
    shipping: {
      weight: 0.2,
      dimensions: {
        width: 0.1,
        height: 0.03,
        depth: 0.1,
      },
    },
    productDescription: {
      main: 'A small dish perfect for holding jewelry or trinkets.',
      descOne: 'Handcrafted with delicate detailing.',
      descTwo: 'Comes in multiple shapes and sizes.',
      descThree: 'Perfect for bedside tables or dressers.',
    },
    productDimensions: {
      height: '2.54 cm',
      weight: '0.15 kg',
      depth: '10.16 cm',
    },
  },
  {
    id: 19,
    name: 'Ceramic Plant Pot',
    slug: 'Ceramic-Plant-Pot',
    brand: 'GreenScape',
    productImage:'Ceramics/ceramicNineteen.webp',
    productTitle: 'Minimalist Ceramic Plant Pot',
    productPrice: 32.5,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 18,
    ratings: 4.7,
    tags: ['plant pot', 'minimalist', 'ceramic'],
    colors: ['Gray', 'Matte Black'],
    shipping: {
      weight: 0.9,
      dimensions: {
        width: 0.12,
        height: 0.15,
        depth: 0.12,
      },
    },
    productDescription: {
      main: 'A simple and elegant plant pot for indoor use.',
      descOne: 'Features a drainage hole.',
      descTwo: 'Perfect for small plants or succulents.',
      descThree: 'Available in different sizes and colors.',
    },
    productDimensions: {
      height: '12.7 cm',
      weight: '0.65 kg',
      depth: '10.16 cm',
    },
  },
  {
    id: 20,
    name: 'Decorative Ceramic Bowl',
    slug: 'Decorative-Ceramic-Bowl',
    brand: 'CraftedDecor',
    productImage:'Ceramics/ceramicTwenty.webp',
    productTitle: 'Handcrafted Decorative Ceramic Bowl',
    productPrice: 42.75,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 14,
    ratings: 4.8,
    tags: ['decor bowl', 'handcrafted', 'ceramic'],
    colors: ['Blue', 'White'],
    shipping: {
      weight: 0.8,
      dimensions: {
        width: 0.15,
        height: 0.08,
        depth: 0.15,
      },
    },
    productDescription: {
      main: 'A versatile ceramic bowl for decor or serving.',
      descOne: 'Handcrafted by skilled artisans.',
      descTwo: 'Durable and chip-resistant.',
      descThree: 'Available in a variety of patterns.',
    },
    productDimensions: {
      height: '7.62 cm',
      weight: '0.75 kg',
      depth: '15.24 cm',
    },
  },
  {
    id: 21,
    name: 'Ceramic Salad Bowl',
    slug: 'Ceramic-Salad-Bowl',
    brand: 'HarvestHome',
    productImage:'Ceramics/ceramicTwentyOne.webp',
    productTitle: 'Large Ceramic Salad Bowl',
    productPrice: 38.5,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 20,
    ratings: 4.6,
    tags: ['salad bowl', 'kitchen', 'ceramic'],
    colors: ['White', 'Green'],
    shipping: {
      weight: 1.1,
      dimensions: {
        width: 0.25,
        height: 0.1,
        depth: 0.25,
      },
    },
    productDescription: {
      main: 'A beautifully handcrafted bowl perfect for serving salads.',
      descOne: 'Microwave and dishwasher safe.',
      descTwo: 'Features a hand-painted interior.',
      descThree: 'Perfect for large gatherings.',
    },
    productDimensions: {
      height: '10.16 cm',
      weight: '1.2 kg',
      depth: '25.4 cm',
    },
  },
  {
    id: 22,
    name: 'Ceramic Oil Dispenser',
    slug: 'Ceramic-Oil-Dispenser',
    brand: 'OliveBranch',
    productImage:'Ceramics/ceramicTwentyTwo.webp',
    productTitle: 'Stylish Ceramic Oil Dispenser',
    productPrice: 20.99,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 35,
    ratings: 4.5,
    tags: ['oil dispenser', 'kitchen', 'ceramic'],
    colors: ['Matte White', 'Terracotta'],
    shipping: {
      weight: 0.5,
      dimensions: {
        width: 0.07,
        height: 0.15,
        depth: 0.07,
      },
    },
    productDescription: {
      main: 'A modern ceramic dispenser for oils and vinegars.',
      descOne: 'Easy-pour spout with drip-free design.',
      descTwo: 'Matte finish available in multiple colors.',
      descThree: 'Dishwasher safe for easy cleaning.',
    },
    productDimensions: {
      height: '15.24 cm',
      weight: '0.5 kg',
      depth: '6.35 cm',
    },
  },
  {
    id: 23,
    name: 'Ceramic Honey Pot',
    slug: 'Ceramic-Honey-Pot',
    brand: 'SweetHive',
    productImage:'Ceramics/ceramicTwentyThree.webp',
    productTitle: 'Traditional Ceramic Honey Pot',
    productPrice: 16.99,
    category: 'ceramics',
    material: 'Earthenware',
    isAvailable: true,
    stock: 18,
    ratings: 4.4,
    tags: ['honey pot', 'kitchen', 'ceramic'],
    colors: ['Yellow', 'Brown'],
    shipping: {
      weight: 0.3,
      dimensions: {
        width: 0.09,
        height: 0.12,
        depth: 0.09,
      },
    },
    productDescription: {
      main: 'A charming ceramic honey pot with a wooden dipper.',
      descOne: 'Perfect for storing honey or syrups.',
      descTwo: 'Features a secure lid to keep contents fresh.',
      descThree: 'Available in multiple rustic designs.',
    },
    productDimensions: {
      height: '12.7 cm',
      weight: '0.3 kg',
      depth: '8.89 cm',
    },
  },
  {
    id: 24,
    name: 'Ceramic Pasta Bowl',
    slug: 'Ceramic-Pasta-Bowl',
    brand: 'CulinaryArts',
    productImage:'Ceramics/ceramicTwentyFour.webp',
    productTitle: 'Large Ceramic Pasta Bowl',
    productPrice: 28.99,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 15,
    ratings: 4.7,
    tags: ['pasta bowl', 'kitchen', 'ceramic'],
    colors: ['Blue', 'Ivory'],
    shipping: {
      weight: 0.7,
      dimensions: {
        width: 0.22,
        height: 0.08,
        depth: 0.22,
      },
    },
    productDescription: {
      main: 'A wide ceramic bowl perfect for serving pasta.',
      descOne: 'Microwave and oven safe.',
      descTwo: 'Smooth glaze finish for easy cleaning.',
      descThree: 'Available in multiple color options.',
    },
    productDimensions: {
      height: '7.62 cm',
      weight: '0.68 kg',
      depth: '22.86 cm',
    },
  },
  {
    id: 25,
    name: 'Ceramic Tea Infuser',
    slug: 'Ceramic-Tea-Infuser',
    brand: 'ZenBrew',
    productImage:'Ceramics/ceramicTwentyFive.webp',
    productTitle: 'Elegant Ceramic Tea Infuser',
    productPrice: 15.5,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 30,
    ratings: 4.3,
    tags: ['tea infuser', 'beverage', 'ceramic'],
    colors: ['Mint Green', 'Lavender'],
    shipping: {
      weight: 0.4,
      dimensions: {
        width: 0.08,
        height: 0.1,
        depth: 0.08,
      },
    },
    productDescription: {
      main: 'A small ceramic cup with a built-in infuser for loose leaf tea.',
      descOne: 'Includes a matching lid to keep tea warm.',
      descTwo: 'Dishwasher safe and heat-resistant.',
      descThree: 'Available in multiple pastel colors.',
    },
    productDimensions: {
      height: '10.16 cm',
      weight: '0.4 kg',
      depth: '7.62 cm',
    },
  },
  {
    id: 26,
    name: 'Ceramic Snack Tray',
    slug: 'Ceramic-Snack-Tray',
    brand: 'HostEssentials',
    productImage:'Ceramics/ceramicTwentySix.webp',
    productTitle: 'Contemporary Ceramic Snack Tray',
    productPrice: 22.99,
    category: 'ceramics',
    material: 'Earthenware',
    isAvailable: true,
    stock: 12,
    ratings: 4.4,
    tags: ['snack tray', 'kitchen', 'ceramic'],
    colors: ['Gray', 'White'],
    shipping: {
      weight: 0.8,
      dimensions: {
        width: 0.25,
        height: 0.03,
        depth: 0.25,
      },
    },
    productDescription: {
      main: 'A sleek and modern tray perfect for snacks or appetizers.',
      descOne: 'Features multiple compartments for easy organization.',
      descTwo: 'Durable and chip-resistant.',
      descThree: 'Available in both white and gray finishes.',
    },
    productDimensions: {
      height: '2.54 cm',
      weight: '0.75 kg',
      depth: '30.48 cm',
    },
  },
  {
    id: 27,
    name: 'Ceramic Tart Dish',
    slug: 'Ceramic-Tart-Dish',
    brand: 'BakeCraft',
    productImage:'Ceramics/ceramicTwentySeven.webp',
    productTitle: 'Rustic Ceramic Tart Dish',
    productPrice: 24.99,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 10,
    ratings: 4.6,
    tags: ['tart dish', 'baking', 'ceramic'],
    colors: ['Terracotta', 'White'],
    shipping: {
      weight: 0.85,
      dimensions: {
        width: 0.23,
        height: 0.04,
        depth: 0.23,
      },
    },
    productDescription: {
      main: 'A durable dish perfect for baking tarts or pies.',
      descOne: 'Oven, microwave, and dishwasher safe.',
      descTwo: 'Rustic hand-painted finish.',
      descThree: 'Available in multiple sizes and colors.',
    },
    productDimensions: {
      height: '3.81 cm',
      weight: '0.85 kg',
      depth: '22.86 cm',
    },
  },
  {
    id: 28,
    name: 'Ceramic Mixing Bowl Set',
    slug: 'Ceramic-Mixing-Bowl-Set',
    brand: "Baker'sChoice",
    productImage:'Ceramics/ceramicTwentyEight.webp',
    productTitle: 'Set of 3 Ceramic Mixing Bowls',
    productPrice: 45.0,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 8,
    ratings: 4.8,
    tags: ['mixing bowls', 'kitchen', 'ceramic'],
    colors: ['Navy Blue', 'Ivory'],
    shipping: {
      weight: 2.0,
      dimensions: {
        width: 0.3,
        height: 0.12,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A set of 3 nesting bowls for mixing or serving.',
      descOne: 'Durable and easy to clean.',
      descTwo: 'Features a smooth glaze finish.',
      descThree: 'Perfect for baking or meal prep.',
    },
    productDimensions: {
      height: '12.7 cm',
      weight: '2.0 kg',
      depth: '30.48 cm',
    },
  },
  {
    id: 29,
    name: 'Ceramic Gravy Boat',
    slug: 'Ceramic-Gravy-Boat',
    brand: 'TableElegance',
    productImage:'Ceramics/ceramicTwentyNine.webp',
    productTitle: 'Classic Ceramic Gravy Boat',
    productPrice: 18.99,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 15,
    ratings: 4.5,
    tags: ['gravy boat', 'dining', 'ceramic'],
    colors: ['White', 'Light Blue'],
    shipping: {
      weight: 0.5,
      dimensions: {
        width: 0.2,
        height: 0.07,
        depth: 0.1,
      },
    },
    productDescription: {
      main: 'A classic ceramic gravy boat with a sleek design.',
      descOne: 'Perfect for serving gravies and sauces.',
      descTwo: 'Features an easy-pour spout.',
      descThree: 'Microwave and dishwasher safe.',
    },
    productDimensions: {
      height: '7.62 cm',
      weight: '0.45 kg',
      depth: '20.32 cm',
    },
  },
  {
    id: 30,
    name: 'Ceramic Salt and Pepper Shakers',
    slug: 'Ceramic-Salt-and-Pepper-Shakers',
    brand: 'SpiceArts',
    productImage:'Ceramics/ceramicThirty.webp',
    productTitle: 'Vintage Ceramic Salt and Pepper Shakers',
    productPrice: 12.75,
    category: 'ceramics',
    material: 'Earthenware',
    isAvailable: true,
    stock: 25,
    ratings: 4.6,
    tags: ['salt shaker', 'pepper shaker', 'vintage'],
    colors: ['White', 'Red'],
    shipping: {
      weight: 0.3,
      dimensions: {
        width: 0.08,
        height: 0.1,
        depth: 0.08,
      },
    },
    productDescription: {
      main: 'A charming set of ceramic salt and pepper shakers.',
      descOne: 'Features a vintage floral design.',
      descTwo: 'Easy to refill with removable stoppers.',
      descThree: 'Available in multiple color schemes.',
    },
    productDimensions: {
      height: '7.62 cm',
      weight: '0.25 kg',
      depth: '5.08 cm',
    },
  },
  {
    id: 31,
    name: 'Ceramic Fruit Bowl',
    slug: 'Ceramic-Fruit-Bowl',
    brand: 'NatureCraft',
    productImage:'Ceramics/ceramicThirtyOne.webp',
    productTitle: 'Handmade Ceramic Fruit Bowl',
    productPrice: 35.5,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 20,
    ratings: 4.8,
    tags: ['fruit bowl', 'kitchen decor', 'handmade'],
    colors: ['Green', 'Terracotta'],
    shipping: {
      weight: 1.2,
      dimensions: {
        width: 0.3,
        height: 0.1,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A spacious fruit bowl handcrafted by local artisans.',
      descOne: 'Perfect for displaying fresh fruits on your kitchen counter.',
      descTwo: 'Durable and chip-resistant.',
      descThree: 'Available in different colors.',
    },
    productDimensions: {
      height: '10.16 cm',
      weight: '1.0 kg',
      depth: '30.48 cm',
    },
  },
  {
    id: 32,
    name: 'Ceramic Serving Dish',
    slug: 'Ceramic-Serving-Dish',
    brand: 'TableTopGrace',
    productImage:'Ceramics/ceramicThirtyTwo.webp',
    productTitle: 'Large Ceramic Serving Dish',
    productPrice: 40.0,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 10,
    ratings: 4.5,
    tags: ['serving dish', 'dining', 'ceramic'],
    colors: ['White', 'Light Gray'],
    shipping: {
      weight: 1.4,
      dimensions: {
        width: 0.35,
        height: 0.05,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'An elegant serving dish perfect for large gatherings.',
      descOne: 'Microwave and oven safe.',
      descTwo: 'Features a glossy finish for easy cleaning.',
      descThree: 'Ideal for serving appetizers or main courses.',
    },
    productDimensions: {
      height: '5.08 cm',
      weight: '1.5 kg',
      depth: '35.56 cm',
    },
  },
  {
    id: 33,
    name: 'Ceramic Bread Basket',
    slug: 'Ceramic-Bread-Basket',
    brand: 'RusticTable',
    productImage:'Ceramics/ceramicThirtyThree.webp',
    productTitle: 'Rustic Ceramic Bread Basket',
    productPrice: 32.75,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 12,
    ratings: 4.4,
    tags: ['bread basket', 'dining', 'ceramic'],
    colors: ['Cream', 'Brown'],
    shipping: {
      weight: 0.9,
      dimensions: {
        width: 0.3,
        height: 0.08,
        depth: 0.25,
      },
    },
    productDescription: {
      main: 'A beautifully crafted ceramic bread basket.',
      descOne: 'Hand-painted with unique designs.',
      descTwo: 'Perfect for serving fresh bread at the table.',
      descThree: 'Dishwasher safe.',
    },
    productDimensions: {
      height: '8.89 cm',
      weight: '0.9 kg',
      depth: '33.02 cm',
    },
  },
  {
    id: 34,
    name: 'Ceramic Ice Cream Bowl',
    slug: 'Ceramic-Ice-Cream-Bowl',
    brand: 'FrostyDelights',
    productImage:'Ceramics/ceramicThirtyFour.webp',
    productTitle: 'Set of 4 Ceramic Ice Cream Bowls',
    productPrice: 20.0,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 18,
    ratings: 4.6,
    tags: ['ice cream bowl', 'dessert', 'ceramic'],
    colors: ['Pastel Pink', 'Pastel Blue'],
    shipping: {
      weight: 0.3,
      dimensions: {
        width: 0.15,
        height: 0.05,
        depth: 0.15,
      },
    },
    productDescription: {
      main: 'A set of 4 ceramic bowls perfect for ice cream and desserts.',
      descOne: 'Features a smooth matte finish.',
      descTwo: 'Microwave and dishwasher safe.',
      descThree: 'Available in multiple colors.',
    },
    productDimensions: {
      height: '5.08 cm',
      weight: '0.25 kg per bowl',
      depth: '12.7 cm',
    },
  },
  {
    id: 35,
    name: 'Ceramic Soup Tureen',
    slug: 'Ceramic-Soup-Tureen',
    brand: 'ClassicHome',
    productImage:'Ceramics/ceramicThirtyFive.webp',
    productTitle: 'Traditional Ceramic Soup Tureen',
    productPrice: 55.99,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 5,
    ratings: 4.7,
    tags: ['soup tureen', 'kitchen', 'ceramic'],
    colors: ['Off-White', 'Beige'],
    shipping: {
      weight: 2.0,
      dimensions: {
        width: 0.28,
        height: 0.15,
        depth: 0.18,
      },
    },
    productDescription: {
      main: 'A large ceramic soup tureen perfect for family dinners.',
      descOne: 'Comes with a matching ladle.',
      descTwo: 'Dishwasher and oven safe.',
      descThree: 'Features a hand-painted floral design.',
    },
    productDimensions: {
      height: '15.24 cm',
      weight: '2.0 kg',
      depth: '28.58 cm',
    },
  },
  {
    id: 36,
    name: 'Ceramic Salad Plates',
    slug: 'Ceramic-Salad-Plates',
    brand: 'RusticPlates',
    productImage:'Ceramics/ceramicThirtySix.webp',
    productTitle: 'Set of 6 Ceramic Salad Plates',
    productPrice: 45.0,
    category: 'ceramics',
    material: 'Earthenware',
    isAvailable: true,
    stock: 25,
    ratings: 4.8,
    tags: ['salad plates', 'dining', 'ceramic'],
    colors: ['Green', 'Olive'],
    shipping: {
      weight: 0.6,
      dimensions: {
        width: 0.22,
        height: 0.03,
        depth: 0.22,
      },
    },
    productDescription: {
      main: 'A set of 6 salad plates with a rustic charm.',
      descOne: 'Perfect for serving salads or appetizers.',
      descTwo: 'Durable and microwave safe.',
      descThree: 'Available in a variety of patterns.',
    },
    productDimensions: {
      height: '2.54 cm',
      weight: '0.6 kg per plate',
      depth: '22.86 cm',
    },
  },
  {
    id: 37,
    name: 'Ceramic Soup Mugs',
    slug: 'Ceramic-Soup-Mugs',
    brand: 'MugMaster',
    productImage:'Ceramics/ceramicThirtySeven.webp',
    productTitle: 'Set of 4 Ceramic Soup Mugs',
    productPrice: 35.0,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 30,
    ratings: 4.9,
    tags: ['soup mugs', 'kitchen', 'ceramic'],
    colors: ['Charcoal', 'Cream'],
    shipping: {
      weight: 0.5,
      dimensions: {
        width: 0.12,
        height: 0.09,
        depth: 0.12,
      },
    },
    productDescription: {
      main: 'A set of 4 large soup mugs with handles.',
      descOne: 'Perfect for soups, stews, and hot drinks.',
      descTwo: 'Microwave and oven safe.',
      descThree: 'Dishwasher safe and durable.',
    },
    productDimensions: {
      height: '9.53 cm',
      weight: '0.5 kg per mug',
      depth: '12.7 cm',
    },
  },
  {
    id: 38,
    name: 'Ceramic Chip and Dip Set',
    slug: 'Ceramic-Chip-and-Dip-Set',
    brand: 'PartyPerfect',
    productImage:'Ceramics/ceramicThirtyEight.webp',
    productTitle: 'Ceramic Chip and Dip Serving Set',
    productPrice: 28.99,
    category: 'ceramics',
    material: 'Earthenware',
    isAvailable: true,
    stock: 20,
    ratings: 4.6,
    tags: ['chip and dip', 'serving', 'ceramic'],
    colors: ['White', 'Slate Gray'],
    shipping: {
      weight: 0.8,
      dimensions: {
        width: 0.25,
        height: 0.05,
        depth: 0.25,
      },
    },
    productDescription: {
      main: 'A versatile ceramic serving set for chips and dips.',
      descOne: 'Durable and easy to clean.',
      descTwo: 'Microwave safe for reheating dips.',
      descThree: 'Comes with a matching dip bowl.',
    },
    productDimensions: {
      height: '5.08 cm',
      weight: '0.8 kg',
      depth: '25.4 cm',
    },
  },
  {
    id: 39,
    name: 'Ceramic Rice Bowl',
    slug: 'Ceramic-Rice-Bowl',
    brand: 'NatureEssence',
    productImage:'Ceramics/ceramicThirtyNine.webp',
    productTitle: 'Handmade Ceramic Rice Bowl',
    productPrice: 15.5,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 25,
    ratings: 4.5,
    tags: ['rice bowl', 'kitchen', 'ceramic'],
    colors: ['Sage Green', 'Cream'],
    shipping: {
      weight: 0.4,
      dimensions: {
        width: 0.15,
        height: 0.06,
        depth: 0.15,
      },
    },
    productDescription: {
      main: 'A handcrafted ceramic bowl perfect for rice and grains.',
      descOne: 'Features a rustic glaze finish.',
      descTwo: 'Dishwasher and microwave safe.',
      descThree: 'Available in different sizes.',
    },
    productDimensions: {
      height: '6.35 cm',
      weight: '0.4 kg',
      depth: '15.24 cm',
    },
  },
  {
    id: 40,
    name: 'Ceramic Gravy Jug',
    slug: 'Ceramic-Gravy-Jug',
    brand: 'SauceCraft',
    productImage:'Ceramics/ceramicForty.webp',
    productTitle: 'Classic Ceramic Gravy Jug',
    productPrice: 22.5,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 18,
    ratings: 4.7,
    tags: ['gravy jug', 'serving', 'ceramic'],
    colors: ['Ivory', 'Gray'],
    shipping: {
      weight: 0.5,
      dimensions: {
        width: 0.17,
        height: 0.1,
        depth: 0.17,
      },
    },
    productDescription: {
      main: 'A classic ceramic gravy jug perfect for serving sauces.',
      descOne: 'Features an easy-pour spout.',
      descTwo: 'Microwave and dishwasher safe.',
      descThree: 'Available in white or gray finishes.',
    },
    productDimensions: {
      height: '10.16 cm',
      weight: '0.45 kg',
      depth: '17.78 cm',
    },
  },
  {
    id: 41,
    name: 'Ceramic Cookie Jar',
    slug: 'Ceramic-Cookie-Jar',
    brand: 'CookieCraft',
    productImage:'Ceramics/ceramicFortyOne.webp',
    productTitle: 'Vintage Ceramic Cookie Jar',
    productPrice: 38.99,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 10,
    ratings: 4.8,
    tags: ['cookie jar', 'storage', 'ceramic'],
    colors: ['Pastel Green', 'Beige'],
    shipping: {
      weight: 1.0,
      dimensions: {
        width: 0.2,
        height: 0.22,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'A vintage-style ceramic jar perfect for storing cookies.',
      descOne: 'Features a tight-sealing lid to keep contents fresh.',
      descTwo: 'Hand-painted with decorative designs.',
      descThree: 'Available in different colors.',
    },
    productDimensions: {
      height: '20.32 cm',
      weight: '1.0 kg',
      depth: '17.78 cm',
    },
  },
  {
    id: 42,
    name: 'Ceramic Pie Dish',
    slug: 'Ceramic-Pie-Dish',
    brand: 'BakeWell',
    productImage:'Ceramics/ceramicFortyTwo.webp',
    productTitle: 'Rustic Ceramic Pie Dish',
    productPrice: 25.99,
    category: 'ceramics',
    material: 'Earthenware',
    isAvailable: true,
    stock: 22,
    ratings: 4.7,
    tags: ['pie dish', 'baking', 'ceramic'],
    colors: ['White', 'Blue'],
    shipping: {
      weight: 0.9,
      dimensions: {
        width: 0.23,
        height: 0.05,
        depth: 0.23,
      },
    },
    productDescription: {
      main: 'A rustic ceramic dish perfect for baking pies and tarts.',
      descOne: 'Microwave, oven, and dishwasher safe.',
      descTwo: 'Durable and scratch-resistant.',
      descThree: 'Available in multiple colors.',
    },
    productDimensions: {
      height: '5.08 cm',
      weight: '0.9 kg',
      depth: '22.86 cm',
    },
  },
  {
    id: 43,
    name: 'Ceramic Mug with Saucer',
    slug: 'Ceramic-Mug-with-Saucer',
    brand: 'SippingElegance',
    productImage:'Ceramics/ceramicFortyThree.webp',
    productTitle: 'Modern Ceramic Mug with Saucer',
    productPrice: 18.99,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 20,
    ratings: 4.6,
    tags: ['mug with saucer', 'drinkware', 'ceramic'],
    colors: ['White', 'Soft Blue'],
    shipping: {
      weight: 0.4,
      dimensions: {
        width: 0.12,
        height: 0.1,
        depth: 0.12,
      },
    },
    productDescription: {
      main: 'A stylish ceramic mug paired with a matching saucer.',
      descOne: 'Perfect for serving tea or coffee.',
      descTwo: 'Microwave and dishwasher safe.',
      descThree: 'Available in multiple colors.',
    },
    productDimensions: {
      height: '10.16 cm',
      weight: '0.4 kg',
      depth: '7.62 cm',
    },
  },
  {
    id: 44,
    name: 'Ceramic Pet Bowl',
    slug: 'Ceramic-Pet-Bowl',
    brand: 'PetCrafters',
    productImage:'Ceramics/ceramicFortyFour.webp',
    productTitle: 'Handcrafted Ceramic Pet Bowl',
    productPrice: 12.99,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 35,
    ratings: 4.5,
    tags: ['pet bowl', 'ceramic', 'handmade'],
    colors: ['Blue', 'Tan'],
    shipping: {
      weight: 0.5,
      dimensions: {
        width: 0.15,
        height: 0.06,
        depth: 0.15,
      },
    },
    productDescription: {
      main: 'A handcrafted ceramic bowl perfect for pets.',
      descOne: 'Durable and dishwasher safe.',
      descTwo: 'Non-slip base for added stability.',
      descThree: 'Available in multiple sizes and colors.',
    },
    productDimensions: {
      height: '6.35 cm',
      weight: '0.5 kg',
      depth: '15.24 cm',
    },
  },
  {
    id: 45,
    name: 'Ceramic Dipping Bowls',
    slug: 'Ceramic-Dipping-Bowls',
    brand: 'TableTrends',
    productImage:'Ceramics/ceramicFortyFive.webp',
    productTitle: 'Set of 4 Ceramic Dipping Bowls',
    productPrice: 20.5,
    category: 'ceramics',
    material: 'Earthenware',
    isAvailable: true,
    stock: 45,
    ratings: 4.4,
    tags: ['dipping bowls', 'serving', 'ceramic'],
    colors: ['White', 'Assorted'],
    shipping: {
      weight: 0.25,
      dimensions: {
        width: 0.08,
        height: 0.04,
        depth: 0.08,
      },
    },
    productDescription: {
      main: 'A set of 4 small ceramic bowls perfect for dips and sauces.',
      descOne: 'Microwave and dishwasher safe.',
      descTwo: 'Comes in a variety of vibrant colors.',
      descThree: 'Durable and easy to clean.',
    },
    productDimensions: {
      height: '3.81 cm',
      weight: '0.25 kg per bowl',
      depth: '7.62 cm',
    },
  },
  {
    id: 46,
    name: 'Ceramic Cheese Board',
    slug: 'Ceramic-Cheese-Board',
    brand: 'CheeseMate',
    productImage:'Ceramics/ceramicFortySix.webp',
    productTitle: 'Elegant Ceramic Cheese Board',
    productPrice: 30.75,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 30,
    ratings: 4.7,
    tags: ['cheese board', 'serving', 'ceramic'],
    colors: ['White', 'Black'],
    shipping: {
      weight: 1.2,
      dimensions: {
        width: 0.3,
        height: 0.02,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A beautifully crafted ceramic cheese board.',
      descOne: 'Perfect for serving cheeses and charcuterie.',
      descTwo: 'Features a glossy, non-porous surface.',
      descThree: 'Available in both rectangular and circular shapes.',
    },
    productDimensions: {
      height: '2.54 cm',
      weight: '1.2 kg',
      depth: '30.48 cm',
    },
  },
  {
    id: 47,
    name: 'Ceramic Sauce Bowl',
    slug: 'Ceramic-Sauce-Bowl',
    brand: 'SaucyServe',
    productImage:'Ceramics/ceramicFortySeven.webp',
    productTitle: 'Small Ceramic Sauce Bowl',
    productPrice: 10.99,
    category: 'ceramics',
    material: 'Earthenware',
    isAvailable: true,
    stock: 50,
    ratings: 4.3,
    tags: ['sauce bowl', 'kitchen', 'ceramic'],
    colors: ['Cream', 'Terracotta'],
    shipping: {
      weight: 0.15,
      dimensions: {
        width: 0.1,
        height: 0.04,
        depth: 0.1,
      },
    },
    productDescription: {
      main: 'A small ceramic bowl ideal for serving sauces and dressings.',
      descOne: 'Handcrafted with a rustic finish.',
      descTwo: 'Microwave and dishwasher safe.',
      descThree: 'Available in multiple colors.',
    },
    productDimensions: {
      height: '3.81 cm',
      weight: '0.15 kg',
      depth: '10.16 cm',
    },
  },
  {
    id: 48,
    name: 'Ceramic Spoon Rest',
    slug: 'Ceramic-Spoon-Rest',
    brand: 'CookEase',
    productImage:'Ceramics/ceramicFortyEight.webp',
    productTitle: 'Handmade Ceramic Spoon Rest',
    productPrice: 9.99,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 60,
    ratings: 4.6,
    tags: ['spoon rest', 'kitchen', 'ceramic'],
    colors: ['White', 'Light Blue'],
    shipping: {
      weight: 0.2,
      dimensions: {
        width: 0.13,
        height: 0.03,
        depth: 0.13,
      },
    },
    productDescription: {
      main: 'A handcrafted ceramic spoon rest for kitchen use.',
      descOne: 'Keeps your counters clean while cooking.',
      descTwo: 'Durable and easy to clean.',
      descThree: 'Available in multiple colors.',
    },
    productDimensions: {
      height: '2.54 cm',
      weight: '0.2 kg',
      depth: '12.7 cm',
    },
  },
  {
    id: 49,
    name: 'Ceramic Cereal Bowls',
    slug: 'Ceramic-Cereal-Bowls',
    brand: 'BowlEssence',
    productImage:'Ceramics/ceramicFortyNine.webp',
    productTitle: 'Set of 4 Ceramic Cereal Bowls',
    productPrice: 28.99,
    category: 'ceramics',
    material: 'Earthenware',
    isAvailable: true,
    stock: 40,
    ratings: 4.8,
    tags: ['cereal bowls', 'dining', 'ceramic'],
    colors: ['Pastel Pink', 'Gray'],
    shipping: {
      weight: 0.35,
      dimensions: {
        width: 0.15,
        height: 0.06,
        depth: 0.15,
      },
    },
    productDescription: {
      main: 'A set of 4 ceramic bowls perfect for cereal or soups.',
      descOne: 'Microwave and dishwasher safe.',
      descTwo: 'Available in multiple colors and patterns.',
      descThree: 'Durable and easy to clean.',
    },
    productDimensions: {
      height: '6.35 cm',
      weight: '0.35 kg per bowl',
      depth: '15.24 cm',
    },
  },
  {
    id: 50,
    name: 'Ceramic Butter Keeper',
    slug: 'Ceramic-Butter-Keeper',
    brand: 'Butterly',
    productImage:'Ceramics/ceramicFifty.webp',
    productTitle: 'Vintage Ceramic Butter Keeper',
    productPrice: 19.99,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 35,
    ratings: 4.5,
    tags: ['butter keeper', 'kitchen', 'ceramic'],
    colors: ['Beige', 'Pastel Green'],
    shipping: {
      weight: 0.35,
      dimensions: {
        width: 0.1,
        height: 0.08,
        depth: 0.1,
      },
    },
    productDescription: {
      main: 'A vintage-style ceramic butter keeper with a lid.',
      descOne: 'Perfect for keeping butter fresh at room temperature.',
      descTwo: 'Dishwasher safe for easy cleaning.',
      descThree: 'Available in multiple colors.',
    },
    productDimensions: {
      height: '8.89 cm',
      weight: '0.35 kg',
      depth: '10.16 cm',
    },
  },
  {
    id: 51,
    name: 'Ceramic Spice Jars',
    slug: 'Ceramic-Spice-Jars',
    brand: 'SpiceCharm',
    productImage:'Ceramics/ceramicFiftyOne.webp',
    productTitle: 'Set of 6 Ceramic Spice Jars',
    productPrice: 24.99,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 55,
    ratings: 4.7,
    tags: ['spice jars', 'kitchen', 'ceramic'],
    colors: ['White', 'Assorted Patterns'],
    shipping: {
      weight: 0.3,
      dimensions: {
        width: 0.06,
        height: 0.07,
        depth: 0.06,
      },
    },
    productDescription: {
      main: 'A set of 6 ceramic jars perfect for storing spices.',
      descOne: 'Comes with airtight lids to keep spices fresh.',
      descTwo: 'Available in various colors and patterns.',
      descThree: 'Dishwasher safe for easy cleaning.',
    },
    productDimensions: {
      height: '7.62 cm',
      weight: '0.3 kg per jar',
      depth: '5.08 cm',
    },
  },
  {
    id: 52,
    name: 'Ceramic Coffee Canister',
    slug: 'Ceramic-Coffee-Canister',
    brand: 'BrewBuddy',
    productImage:'Ceramics/ceramicFiftyTwo.webp',
    productTitle: 'Large Ceramic Coffee Canister',
    productPrice: 29.99,
    category: 'ceramics',
    material: 'Stoneware',
    isAvailable: true,
    stock: 30,
    ratings: 4.6,
    tags: ['coffee canister', 'kitchen', 'ceramic'],
    colors: ['White', 'Natural'],
    shipping: {
      weight: 0.7,
      dimensions: {
        width: 0.1,
        height: 0.15,
        depth: 0.1,
      },
    },
    productDescription: {
      main: 'A stylish ceramic canister for storing coffee or tea.',
      descOne: 'Features a tight-sealing wooden lid.',
      descTwo: 'Available in different sizes and colors.',
      descThree: 'Dishwasher safe for easy cleaning.',
    },
    productDimensions: {
      height: '15.24 cm',
      weight: '0.7 kg',
      depth: '10.16 cm',
    },
  },
  {
    id: 53,
    name: 'Ceramic Ramekins',
    slug: 'Ceramic-Ramekins',
    brand: 'BakingBuddies',
    productImage:'Ceramics/ceramicFiftyThree.webp',
    productTitle: 'Set of 4 Ceramic Ramekins',
    productPrice: 18.5,
    category: 'ceramics',
    material: 'Porcelain',
    isAvailable: true,
    stock: 50,
    ratings: 4.9,
    tags: ['ramekins', 'baking', 'ceramic'],
    colors: ['White', 'Beige'],
    shipping: {
      weight: 0.2,
      dimensions: {
        width: 0.09,
        height: 0.04,
        depth: 0.09,
      },
    },
    productDescription: {
      main: 'A set of 4 ceramic ramekins ideal for baking and serving.',
      descOne: 'Oven, microwave, and dishwasher safe.',
      descTwo: 'Perfect for soufflés, crème brûlée, and more.',
      descThree: 'Available in multiple colors.',
    },
    productDimensions: {
      height: '4.45 cm',
      weight: '0.2 kg per ramekin',
      depth: '8.89 cm',
    },
  },
];
