import { Product } from 'src/types/Product';

export const lights: Product[] = [
  {
    id: 1,
    name: 'Elegant Lamp',
    slug: 'Elegant-Lamp',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightOne.webp',
    productTitle: 'Stylish Lamp Model 1',
    productPrice: 40.12,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 34,
    ratings: 4.6,
    tags: ['Energy Efficient', 'Modern'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.5,
        height: 0.7,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '80 cm',
      weight: '1 kg',
      depth: '28 cm',
    },
  },
  {
    id: 2,
    name: 'Solar Drift',
    slug: 'Solar-Drift',
    brand: 'Eco Glow',
    productImage:'Lights/lightTwo.webp',
    productTitle: 'Stylish Lamp Model 2',
    productPrice: 70.5,
    category: 'lights',
    material: 'Metal',
    isAvailable: true,
    stock: 15,
    ratings: 4.3,
    tags: ['LED', 'Energy Efficient'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.6,
        height: 1.2,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '75 cm',
      weight: '6 kg',
      depth: '40 cm',
    },
  },
  {
    id: 3,
    name: 'Nimbus Beam',
    slug: 'Nimbus-Beam',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightThree.webp',
    productTitle: 'Stylish Lamp Model 3',
    productPrice: 85.99,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 48,
    ratings: 4.9,
    tags: ['Energy Efficient'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.7,
        height: 1.1,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '68 cm',
      weight: '5 kg',
      depth: '37 cm',
    },
  },
  {
    id: 4,
    name: 'Luna Spark',
    slug: 'Luna-Spark',
    brand: 'Eco Glow',
    productImage:'Lights/lightFour.webp',
    productTitle: 'Stylish Lamp Model 4',
    productPrice: 120.0,
    category: 'lights',
    material: 'Glass',
    isAvailable: true,
    stock: 22,
    ratings: 3.4,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 7,
      dimensions: {
        width: 0.8,
        height: 1.5,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '90 cm',
      weight: '4 kg',
      depth: '35 cm',
    },
  },
  {
    id: 5,
    name: 'Ember Wave',
    slug: 'Ember-Wave',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightFive.webp',
    productTitle: 'Stylish Lamp Model 5',
    productPrice: 110.99,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 10,
    ratings: 2.9,
    tags: ['Modern', 'Energy Efficient'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.4,
        height: 1.1,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '73 cm',
      weight: '3 kg',
      depth: '29 cm',
    },
  },
  {
    id: 6,
    name: 'Radiance Arc',
    slug: 'Radiance-Arc',
    brand: 'Eco Glow',
    productImage:'Lights/lightSix.webp',
    productTitle: 'Stylish Lamp Model 6',
    productPrice: 115.49,
    category: 'lights',
    material: 'Metal',
    isAvailable: false,
    stock: 15,
    ratings: 4.5,
    tags: ['LED', 'Energy Efficient'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.8,
        height: 1.3,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '62 cm',
      weight: '6 kg',
      depth: '32 cm',
    },
  },
  {
    id: 7,
    name: 'Nova Bloom',
    slug: 'Nova-Bloom',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightSeven.webp',
    productTitle: 'Stylish Lamp Model 7',
    productPrice: 98.6,
    category: 'lights',
    material: 'Glass',
    isAvailable: true,
    stock: 50,
    ratings: 2.7,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 4,
      dimensions: {
        width: 0.6,
        height: 1.4,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '91 cm',
      weight: '6 kg',
      depth: '38 cm',
    },
  },
  {
    id: 8,
    name: 'Glimmer Arc',
    slug: 'Glimmer-Arc',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightEight.webp',
    productTitle: 'Stylish Lamp Model 8',
    productPrice: 45.15,
    category: 'lights',
    material: 'Metal',
    isAvailable: true,
    stock: 12,
    ratings: 3.1,
    tags: ['Energy Efficient', 'Modern'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.3,
        height: 0.7,
        depth: 0.6,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '55 cm',
      weight: '3 kg',
      depth: '30 cm',
    },
  },
  {
    id: 9,
    name: 'Halo Breeze',
    slug: 'Halo-Breeze',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightNine.webp',
    productTitle: 'Stylish Lamp Model 9',
    productPrice: 67.72,
    category: 'lights',
    material: 'Plastic',
    isAvailable: false,
    stock: 5,
    ratings: 4.2,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 7,
      dimensions: {
        width: 0.5,
        height: 1.1,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '70 cm',
      weight: '6 kg',
      depth: '34 cm',
    },
  },
  {
    id: 10,
    name: 'Crystal Ray',
    slug: 'Crystal-Ray',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightTen.webp',
    productTitle: 'Stylish Lamp Model 10',
    productPrice: 29.9,
    category: 'lights',
    material: 'Glass',
    isAvailable: true,
    stock: 8,
    ratings: 2.9,
    tags: ['Energy Efficient', 'Modern'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.2,
        height: 0.8,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '65 cm',
      weight: '4 kg',
      depth: '28 cm',
    },
  },
  {
    id: 11,
    name: 'Polaris Shine',
    slug: 'Polaris-Shine',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightEleven.webp',
    productTitle: 'Stylish Lamp Model 11',
    productPrice: 57.85,
    category: 'lights',
    material: 'Metal',
    isAvailable: true,
    stock: 23,
    ratings: 4.4,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.5,
        height: 1.1,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '60 cm',
      weight: '3 kg',
      depth: '28 cm',
    },
  },
  {
    id: 12,
    name: 'Stardust Flare',
    slug: 'Stardust-Flare',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightTwelve.webp',
    productTitle: 'Stylish Lamp Model 12',
    productPrice: 132.75,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 0,
    ratings: 3.2,
    tags: ['Energy Efficient'],
    shipping: {
      weight: 9,
      dimensions: {
        width: 0.8,
        height: 1.1,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '80 cm',
      weight: '4 kg',
      depth: '30 cm',
    },
  },
  {
    id: 13,
    name: 'Dawn Whisper',
    slug: 'Dawn-Whisper',
    brand: 'Eco Glow',
    productImage:'Lights/lightThirteen.webp',
    productTitle: 'Stylish Lamp Model 13',
    productPrice: 112.99,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 14,
    ratings: 2.6,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.3,
        height: 0.8,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '77 cm',
      weight: '5 kg',
      depth: '33 cm',
    },
  },
  {
    id: 14,
    name: 'Twilight Glow',
    slug: 'Twilight-Glow',
    brand: 'Eco Glow',
    productImage:'Lights/lightFourteen.webp',
    productTitle: 'Stylish Lamp Model 14',
    productPrice: 137.52,
    category: 'lights',
    material: 'Glass',
    isAvailable: true,
    stock: 11,
    ratings: 4.1,
    tags: ['Modern', 'Energy Efficient'],
    shipping: {
      weight: 8,
      dimensions: {
        width: 0.6,
        height: 1.5,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '94 cm',
      weight: '6 kg',
      depth: '35 cm',
    },
  },
  {
    id: 15,
    name: 'Prism Pulse',
    slug: 'Prism-Pulse',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightFifteen.webp',
    productTitle: 'Stylish Lamp Model 15',
    productPrice: 66.43,
    category: 'lights',
    material: 'Metal',
    isAvailable: true,
    stock: 33,
    ratings: 1.8,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.7,
        height: 0.9,
        depth: 0.2,
      },
    },
  },
  {
    id: 16,
    name: 'Starfall Light',
    slug: 'Starfall-Light',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightSixteen.webp',
    productTitle: 'Stylish Lamp Model 16',
    productPrice: 78.61,
    category: 'lights',
    material: 'Glass',
    isAvailable: true,
    stock: 24,
    ratings: 3.5,
    tags: ['LED', 'Energy Efficient', 'Modern'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.4,
        height: 1.1,
        depth: 0.6,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '74 cm',
      weight: '5 kg',
      depth: '26 cm',
    },
  },
  {
    id: 17,
    name: 'Ember Light',
    slug: 'Ember-Light',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightSeventeen.webp',
    productTitle: 'Stylish Lamp Model 17',
    productPrice: 112.43,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 28,
    ratings: 4.9,
    tags: ['Energy Efficient'],
    shipping: {
      weight: 7,
      dimensions: {
        width: 0.3,
        height: 1.0,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '67 cm',
      weight: '3 kg',
      depth: '25 cm',
    },
  },
  {
    id: 18,
    name: 'Zenith Glow',
    slug: 'Zenith-Glow',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightEighteen.webp',
    productTitle: 'Stylish Lamp Model 18',
    productPrice: 130.33,
    category: 'lights',
    material: 'Metal',
    isAvailable: false,
    stock: 0,
    ratings: 1.7,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 4,
      dimensions: {
        width: 0.4,
        height: 1.4,
        depth: 0.6,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '69 cm',
      weight: '3 kg',
      depth: '28 cm',
    },
  },
  {
    id: 19,
    name: 'Lumen Flux',
    slug: 'Lumen-Flux',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightNineteen.webp',
    productTitle: 'Stylish Lamp Model 19',
    productPrice: 43.89,
    category: 'lights',
    material: 'Glass',
    isAvailable: true,
    stock: 22,
    ratings: 2.1,
    tags: ['Modern'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.6,
        height: 1.2,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '61 cm',
      weight: '5 kg',
      depth: '32 cm',
    },
  },
  {
    id: 20,
    name: 'Whisper Beam',
    slug: 'Whisper-Beam',
    brand: 'Eco Glow',
    productImage:'Lights/lightTwenty.webp',
    productTitle: 'Stylish Lamp Model 20',
    productPrice: 62.53,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 48,
    ratings: 3.4,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 9,
      dimensions: {
        width: 0.3,
        height: 0.9,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '70 cm',
      weight: '2 kg',
      depth: '25 cm',
    },
  },
  {
    id: 21,
    name: 'Ember Flame',
    slug: 'Ember-Flame',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightTwentyOne.webp',
    productTitle: 'Stylish Lamp Model 21',
    productPrice: 109.95,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 30,
    ratings: 4.7,
    tags: ['Energy Efficient', 'LED'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.7,
        height: 1.3,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '81 cm',
      weight: '3 kg',
      depth: '28 cm',
    },
  },
  {
    id: 22,
    name: 'Radiant Dawn',
    slug: 'Radiant-Dawn',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightTwentyTwo.webp',
    productTitle: 'Stylish Lamp Model 22',
    productPrice: 88.12,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 15,
    ratings: 3.0,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.8,
        height: 1.0,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '64 cm',
      weight: '4 kg',
      depth: '24 cm',
    },
  },
  {
    id: 23,
    name: 'Aether Light',
    slug: 'Aether-Light',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightTwentyThree.webp',
    productTitle: 'Stylish Lamp Model 23',
    productPrice: 125.99,
    category: 'lights',
    material: 'Metal',
    isAvailable: true,
    stock: 12,
    ratings: 4.8,
    tags: ['Energy Efficient', 'Modern'],
    shipping: {
      weight: 4,
      dimensions: {
        width: 0.3,
        height: 1.4,
        depth: 0.6,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '95 cm',
      weight: '5 kg',
      depth: '33 cm',
    },
  },
  {
    id: 24,
    name: 'Mirage Mist',
    slug: 'Mirage-Mist',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightTwentyFour.webp',
    productTitle: 'Stylish Lamp Model 24',
    productPrice: 49.49,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 0,
    ratings: 2.7,
    tags: ['LED'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.6,
        height: 1.2,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '82 cm',
      weight: '4 kg',
      depth: '36 cm',
    },
  },
  {
    id: 25,
    name: 'Velvet Gleam',
    slug: 'Velvet-Gleam',
    brand: 'Eco Glow',
    productImage:'Lights/lightTwentyFive.webp',
    productTitle: 'Stylish Lamp Model 25',
    productPrice: 97.15,
    category: 'lights',
    material: 'Metal',
    isAvailable: true,
    stock: 28,
    ratings: 4.2,
    tags: ['Energy Efficient', 'Modern'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.8,
        height: 1.5,
        depth: 0.6,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '77 cm',
      weight: '5 kg',
      depth: '41 cm',
    },
  },
  {
    id: 26,
    name: 'Arc Wave',
    slug: 'Arc-Wave',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightTwentySix.webp',
    productTitle: 'Stylish Lamp Model 26',
    productPrice: 36.84,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 20,
    ratings: 3.8,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.6,
        height: 0.8,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '71 cm',
      weight: '2 kg',
      depth: '23 cm',
    },
  },
  {
    id: 27,
    name: 'Halo Rise',
    slug: 'Halo-Rise',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightTwentySeven.webp',
    productTitle: 'Stylish Lamp Model 27',
    productPrice: 75.33,
    category: 'lights',
    material: 'Metal',
    isAvailable: false,
    stock: 0,
    ratings: 2.5,
    tags: ['LED'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.4,
        height: 0.9,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '64 cm',
      weight: '4 kg',
      depth: '28 cm',
    },
  },
  {
    id: 28,
    name: 'Misty Halo',
    slug: 'Misty-Halo',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightTwentyEight.webp',
    productTitle: 'Stylish Lamp Model 28',
    productPrice: 69.21,
    category: 'lights',
    material: 'Glass',
    isAvailable: true,
    stock: 19,
    ratings: 3.0,
    tags: ['Energy Efficient'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.6,
        height: 1.1,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '65 cm',
      weight: '2 kg',
      depth: '30 cm',
    },
  },
  {
    id: 29,
    name: 'Arcadia Light',
    slug: 'Arcadia-Light',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightTwentyNine.webp',
    productTitle: 'Stylish Lamp Model 29',
    productPrice: 99.5,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 13,
    ratings: 1.6,
    tags: ['Modern'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.4,
        height: 1.3,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '78 cm',
      weight: '3 kg',
      depth: '32 cm',
    },
  },
  {
    id: 30,
    name: 'Pulse Beam',
    slug: 'Pulse-Beam',
    brand: 'Eco Glow',
    productImage:'Lights/lightThirty.webp',
    productTitle: 'Stylish Lamp Model 30',
    productPrice: 73.65,
    category: 'lights',
    material: 'Metal',
    isAvailable: true,
    stock: 5,
    ratings: 2.2,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.4,
        height: 0.9,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '62 cm',
      weight: '4 kg',
      depth: '29 cm',
    },
  },
  {
    id: 31,
    name: 'Daybreak Shine',
    slug: 'Daybreak-Shine',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightThirtyOne.webp',
    productTitle: 'Stylish Lamp Model 31',
    productPrice: 56.89,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 7,
    ratings: 3.1,
    tags: ['Energy Efficient', 'Modern'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.6,
        height: 1.4,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '65 cm',
      weight: '5 kg',
      depth: '34 cm',
    },
  },
  {
    id: 32,
    name: 'Ether Glow',
    slug: 'Ether-Glow',
    brand: 'Eco Glow',
    productImage:'Lights/lightThirtyTwo.webp',
    productTitle: 'Stylish Lamp Model 32',
    productPrice: 37.12,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 0,
    ratings: 1.9,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 8,
      dimensions: {
        width: 0.8,
        height: 1.2,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '90 cm',
      weight: '4 kg',
      depth: '26 cm',
    },
  },
  {
    id: 33,
    name: 'Aurora Sphere',
    slug: 'Aurora-Sphere',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightThirtyThree.webp',
    productTitle: 'Stylish Lamp Model 33',
    productPrice: 42.56,
    category: 'lights',
    material: 'Metal',
    isAvailable: true,
    stock: 32,
    ratings: 4.1,
    tags: ['LED', 'Energy Efficient'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.6,
        height: 1.5,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '68 cm',
      weight: '3 kg',
      depth: '32 cm',
    },
  },
  {
    id: 34,
    name: 'Zenith Ray',
    slug: 'Zenith-Ray',
    brand: 'Eco Glow',
    productImage:'Lights/lightThirtyFour.webp',
    productTitle: 'Stylish Lamp Model 34',
    productPrice: 92.03,
    category: 'lights',
    material: 'Glass',
    isAvailable: true,
    stock: 16,
    ratings: 4.5,
    tags: ['Modern', 'Energy Efficient'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.5,
        height: 1.4,
        depth: 0.6,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '77 cm',
      weight: '4 kg',
      depth: '31 cm',
    },
  },
  {
    id: 35,
    name: 'Arc Light',
    slug: 'Arc-Light',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightThirtyFive.webp',
    productTitle: 'Stylish Lamp Model 35',
    productPrice: 50.84,
    category: 'lights',
    material: 'Plastic',
    isAvailable: false,
    stock: 4,
    ratings: 2.8,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 4,
      dimensions: {
        width: 0.7,
        height: 1.1,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '63 cm',
      weight: '5 kg',
      depth: '28 cm',
    },
  },
  {
    id: 36,
    name: 'Lunar Ray',
    slug: 'Lunar-Ray',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightThirtySix.webp',
    productTitle: 'Stylish Lamp Model 36',
    productPrice: 72.46,
    category: 'lights',
    material: 'Metal',
    isAvailable: true,
    stock: 23,
    ratings: 4.0,
    tags: ['Modern'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.8,
        height: 1.3,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '70 cm',
      weight: '4 kg',
      depth: '32 cm',
    },
  },
  {
    id: 37,
    name: 'Nebula Aura',
    slug: 'Nebula-Aura',
    brand: 'Eco Glow',
    productImage:'Lights/lightThirtySeven.webp',
    productTitle: 'Stylish Lamp Model 37',
    productPrice: 49.12,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 7,
    ratings: 3.4,
    tags: ['LED'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.6,
        height: 0.9,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '76 cm',
      weight: '3 kg',
      depth: '31 cm',
    },
  },
  {
    id: 38,
    name: 'Glimmer Pulse',
    slug: 'Glimmer-Pulse',
    brand: 'Eco Glow',
    productImage:'Lights/lightThirtyEight.webp',
    productTitle: 'Stylish Lamp Model 38',
    productPrice: 57.37,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 23,
    ratings: 2.3,
    tags: ['LED', 'Energy Efficient', 'Modern'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.33,
        height: 1.18,
        depth: 0.53,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '82 cm',
      weight: '6 kg',
      depth: '50 cm',
    },
  },
  {
    id: 39,
    name: 'Glow Beam',
    slug: 'Glow-Beam',
    brand: 'Eco Glow',
    productImage:'Lights/lightThirtyNine.webp',
    productTitle: 'Stylish Lamp Model 39',
    productPrice: 129.73,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 33,
    ratings: 1.1,
    tags: ['Modern'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.7,
        height: 0.83,
        depth: 0.82,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '88 cm',
      weight: '5 kg',
      depth: '22 cm',
    },
  },
  {
    id: 40,
    name: 'Ember Glow',
    slug: 'Ember-Glow',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightForty.webp',
    productTitle: 'Stylish Lamp Model 40',
    productPrice: 58.22,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 0,
    ratings: 4.4,
    tags: ['Modern'],
    shipping: {
      weight: 7,
      dimensions: {
        width: 0.64,
        height: 0.77,
        depth: 0.32,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '72 cm',
      weight: '5 kg',
      depth: '33 cm',
    },
  },
  {
    id: 41,
    name: 'Solstice Shine',
    slug: 'Solstice-Shine',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightFortyOne.webp',
    productTitle: 'Stylish Lamp Model 41',
    productPrice: 45.84,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 9,
    ratings: 3.6,
    tags: ['Energy Efficient', 'Modern'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.39,
        height: 1.02,
        depth: 0.92,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '95 cm',
      weight: '6 kg',
      depth: '31 cm',
    },
  },
  {
    id: 42,
    name: 'Horizon Spark',
    slug: 'Horizon-Spark',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightFortyTwo.webp',
    productTitle: 'Stylish Lamp Model 42',
    productPrice: 66.76,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 0,
    ratings: 2.2,
    tags: ['Energy Efficient'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.75,
        height: 1.3,
        depth: 0.22,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '95 cm',
      weight: '3 kg',
      depth: '26 cm',
    },
  },
  {
    id: 43,
    name: 'Nova Radiance',
    slug: 'Nova-Radiance',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightFortyThree.webp',
    productTitle: 'Stylish Lamp Model 43',
    productPrice: 32.68,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 14,
    ratings: 4.5,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.29,
        height: 1.22,
        depth: 0.84,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '85 cm',
      weight: '2 kg',
      depth: '21 cm',
    },
  },
  {
    id: 44,
    name: 'Radiant Flux',
    slug: 'Radiant-Flux',
    brand: 'Eco Glow',
    productImage:'Lights/lightFortyFour.webp',
    productTitle: 'Stylish Lamp Model 44',
    productPrice: 46.22,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 5,
    ratings: 2.4,
    tags: ['Modern'],
    shipping: {
      weight: 4,
      dimensions: {
        width: 0.32,
        height: 1.07,
        depth: 0.71,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '68 cm',
      weight: '3 kg',
      depth: '30 cm',
    },
  },
  {
    id: 45,
    name: 'Daylight Gleam',
    slug: 'Daylight-Gleam',
    brand: 'Eco Glow',
    productImage:'Lights/lightFortyFive.webp',
    productTitle: 'Stylish Lamp Model 45',
    productPrice: 55.32,
    category: 'lights',
    material: 'Metal',
    isAvailable: true,
    stock: 16,
    ratings: 3.3,
    tags: ['LED'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.56,
        height: 1.1,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '72 cm',
      weight: '5 kg',
      depth: '29 cm',
    },
  },
  {
    id: 46,
    name: 'Echo Beam',
    slug: 'Echo-Beam',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightFortySix.webp',
    productTitle: 'Stylish Lamp Model 46',
    productPrice: 48.59,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 4,
    ratings: 2.9,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.45,
        height: 0.85,
        depth: 0.34,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '79 cm',
      weight: '4 kg',
      depth: '32 cm',
    },
  },
  {
    id: 47,
    name: 'Gleam Glow',
    slug: 'Gleam-Glow',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightFortySeven.webp',
    productTitle: 'Stylish Lamp Model 47',
    productPrice: 94.88,
    category: 'lights',
    material: 'Plastic',
    isAvailable: false,
    stock: 0,
    ratings: 3.8,
    tags: ['Modern'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.55,
        height: 0.77,
        depth: 0.22,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '60 cm',
      weight: '3 kg',
      depth: '24 cm',
    },
  },
  {
    id: 48,
    name: 'Aether Spark',
    slug: 'Aether-Spark',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightFortyEight.webp',
    productTitle: 'Stylish Lamp Model 48',
    productPrice: 84.73,
    category: 'lights',
    material: 'Glass',
    isAvailable: true,
    stock: 7,
    ratings: 4.0,
    tags: ['LED'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.47,
        height: 1.35,
        depth: 0.21,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '82 cm',
      weight: '4 kg',
      depth: '29 cm',
    },
  },
  {
    id: 49,
    name: 'Celeste Shine',
    slug: 'Celeste-Shine',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightFortyNine.webp',
    productTitle: 'Stylish Lamp Model 49',
    productPrice: 40.22,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 10,
    ratings: 4.9,
    tags: ['Energy Efficient'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.3,
        height: 0.9,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '75 cm',
      weight: '4 kg',
      depth: '28 cm',
    },
  },
  {
    id: 50,
    name: 'Prism Ray',
    slug: 'Prism-Ray',
    brand: 'Eco Glow',
    productImage:'Lights/lightFifty.webp',
    productTitle: 'Stylish Lamp Model 50',
    productPrice: 78.62,
    category: 'lights',
    material: 'Metal',
    isAvailable: false,
    stock: 0,
    ratings: 3.7,
    tags: ['Modern'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.4,
        height: 1.3,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '60 cm',
      weight: '2 kg',
      depth: '22 cm',
    },
  },
  {
    id: 51,
    name: 'Halo Bloom',
    slug: 'Halo-Bloom',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightFiftyOne.webp',
    productTitle: 'Stylish Lamp Model 51',
    productPrice: 59.4,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 17,
    ratings: 2.9,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.55,
        height: 1.3,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '78 cm',
      weight: '3 kg',
      depth: '28 cm',
    },
  },
  {
    id: 52,
    name: 'Arcish Glow',
    slug: 'Arcish-Glow',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightFiftyTwo.webp',
    productTitle: 'Stylish Lamp Model 52',
    productPrice: 69.75,
    category: 'lights',
    material: 'Metal',
    isAvailable: false,
    stock: 0,
    ratings: 3.5,
    tags: ['Modern', 'Energy Efficient'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.47,
        height: 1.2,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '72 cm',
      weight: '4 kg',
      depth: '30 cm',
    },
  },
  {
    id: 53,
    name: 'Pulse Drift',
    slug: 'Pulse-Drift',
    brand: 'Eco Glow',
    productImage:'Lights/lightFiftyThree.webp',
    productTitle: 'Stylish Lamp Model 53',
    productPrice: 36.95,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 0,
    ratings: 2.4,
    tags: ['Energy Efficient'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.6,
        height: 1.1,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '61 cm',
      weight: '3 kg',
      depth: '23 cm',
    },
  },
  {
    id: 54,
    name: 'Whisper Shine',
    slug: 'Whisper-Shine',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightFiftyFour.webp',
    productTitle: 'Stylish Lamp Model 54',
    productPrice: 97.32,
    category: 'lights',
    material: 'Metal',
    isAvailable: true,
    stock: 9,
    ratings: 4.1,
    tags: ['LED'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.5,
        height: 0.9,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '73 cm',
      weight: '2 kg',
      depth: '28 cm',
    },
  },
  {
    id: 55,
    name: 'Nova Horizon',
    slug: 'Nova-Horizon',
    brand: 'Luxe Lighting',
    productImage:'Lights/lightFiftyFive.webp',
    productTitle: 'Stylish Lamp Model 55',
    productPrice: 61.27,
    category: 'lights',
    material: 'Plastic',
    isAvailable: true,
    stock: 11,
    ratings: 4.8,
    tags: ['Energy Efficient'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.4,
        height: 0.6,
        depth: 0.5,
      },
    },
  },
  {
    id: 56,
    name: 'Sunray Glow',
    slug: 'Sunray-Glow',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightFiftySix.webp',
    productTitle: 'Stylish Lamp Model 56',
    productPrice: 41.95,
    category: 'lights',
    material: 'Glass',
    isAvailable: false,
    stock: 0,
    ratings: 2.5,
    tags: ['Modern'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.5,
        height: 0.8,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '75 cm',
      weight: '4 kg',
      depth: '30 cm',
    },
  },
  {
    id: 57,
    name: 'Glimmer Spark',
    slug: 'Glimmer-Spark',
    brand: 'Eco Glow',
    productImage:'Lights/lightFiftySeven.webp',
    productTitle: 'Stylish Lamp Model 57',
    productPrice: 38.74,
    category: 'lights',
    material: 'Metal',
    isAvailable: false,
    stock: 0,
    ratings: 2.3,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.4,
        height: 0.9,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '69 cm',
      weight: '3 kg',
      depth: '28 cm',
    },
  },
  {
    id: 58,
    name: 'Dawn-Radiance',
    slug: 'Dawn-Radiance',
    brand: 'Bright Light Co.',
    productImage:'Lights/lightFiftyEight.webp',
    productTitle: 'Stylish Lamp Model 58',
    productPrice: 81.95,
    category: 'lights',
    material: 'Plastic',
    isAvailable: false,
    stock: 0,
    ratings: 4.4,
    tags: ['LED', 'Modern'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.5,
        height: 0.8,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'An elegant lamp that adds a touch of sophistication to any space.',
      descOne:
        'This lamp features a unique design that complements modern decor.',
      descTwo:
        'It provides excellent illumination with energy-efficient LED bulbs.',
      descThree: 'Ideal for both home and office use.',
    },
    productDimensions: {
      height: '72 cm',
      weight: '4 kg',
      depth: '30 cm',
    },
  },
];
