import { Product } from 'src/types/Product';
export const plants: Product[] = [
  {
    id: 1,
    name: 'Plant-Bambo',
    slug: 'Plant-Bambo',
    brand: 'Green Haven',
    productImage:'Plants/plantOne.webp',
    productTitle: 'Elegant Succulent',
    productPrice: 23.99,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 10,
    ratings: 4.5,
    tags: ['Indoor', 'Succulent'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.3,
        height: 0.5,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'This plant will flourish with minimal care.',
    },
    productDimensions: {
      height: '40 cm',
      weight: '1 kg',
      depth: '30 cm',
    },
  },
  {
    id: 2,
    name: 'Plant Cactus',
    slug: 'Plant-Cactus',
    brand: 'Flora Boutique',
    productImage:'Plants/plantTwo.webp',
    productTitle: 'Beautiful Orchid Plant',
    productPrice: 29.99,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: true,
    stock: 5,
    ratings: 4.8,
    tags: ['Indoor', 'Flowering'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.3,
        height: 0.7,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'Adds a touch of elegance to any space.',
      descOne: 'Requires indirect sunlight and moderate watering.',
      descTwo: 'Blooms beautifully with the right care.',
      descThree: 'Perfect for gifting or home decor.',
    },
    productDimensions: {
      height: '50 cm',
      weight: '1.5 kg',
      depth: '25 cm',
    },
  },
  {
    id: 3,
    name: 'Plant Eucalyptus',
    slug: 'Plant-Eucalyptus',
    brand: 'Plant Paradise',
    productImage:'Plants/plantThree.webp',
    productTitle: 'Charming Potted Cactus',
    productPrice: 15.99,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 20,
    ratings: 4.0,
    tags: ['Outdoor', 'Succulent'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.2,
        height: 0.4,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'A low-maintenance option for any space.',
      descOne: 'Thrives on neglect and loves sunny spots.',
      descTwo: 'Perfect for those who travel often.',
      descThree: 'Adds a unique touch to your decor.',
    },
    productDimensions: {
      height: '25 cm',
      weight: '0.5 kg',
      depth: '20 cm',
    },
  },
  {
    id: 4,
    name: 'Plant Fern',
    slug: 'Plant-Fern',
    brand: 'Green Haven',
    productImage:'Plants/plantFour.webp',
    productTitle: 'Vibrant Green Fern',
    productPrice: 19.99,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 15,
    ratings: 4.2,
    tags: ['Indoor', 'Outdoor'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.4,
        height: 0.8,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'Brings a lush green touch to your home.',
      descOne: 'Prefers indirect sunlight and consistent moisture.',
      descTwo: 'A great air purifier for indoor spaces.',
      descThree: 'Perfect for any room in your home.',
    },
    productDimensions: {
      height: '60 cm',
      weight: '2 kg',
      depth: '30 cm',
    },
  },
  {
    id: 5,
    name: 'Plant-E',
    slug: 'Plant-Rose',
    brand: 'Flora Boutique',
    productImage:'Plants/plantFive.webp',
    productTitle: 'Stunning Flowering Plant',
    productPrice: 35.99,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 8,
    ratings: 4.5,
    tags: ['Flowering', 'Indoor'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.3,
        height: 0.5,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A beautiful flowering plant that brightens any space.',
      descOne: 'Requires moderate sunlight and regular watering.',
      descTwo: 'Perfect for gifting and special occasions.',
      descThree: 'Adds color and charm to your decor.',
    },
    productDimensions: {
      height: '45 cm',
      weight: '1.5 kg',
      depth: '25 cm',
    },
  },
  {
    id: 6,
    name: 'Plant Fiddle',
    slug: 'Plant-Fiddle',
    brand: 'Green Haven',
    productImage:'Plants/plantSix.webp',
    productTitle: 'Elegant Succulent',
    productPrice: 23.99,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 10,
    ratings: 4.5,
    tags: ['Indoor', 'Succulent'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.3,
        height: 0.5,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'This plant will flourish with minimal care.',
    },
    productDimensions: {
      height: '40 cm',
      weight: '1 kg',
      depth: '30 cm',
    },
  },
  {
    id: 7,
    name: 'Plant Philodendron',
    slug: 'Plant-Philodendron',
    brand: 'Flora Boutique',
    productImage:'Plants/plantSeven.webp',
    productTitle: 'Beautiful Philodendron Plant',
    productPrice: 29.99,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: true,
    stock: 5,
    ratings: 4.8,
    tags: ['Indoor', 'Flowering'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.3,
        height: 0.7,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'Adds a touch of elegance to any space.',
      descOne: 'Requires indirect sunlight and moderate watering.',
      descTwo: 'Blooms beautifully with the right care.',
      descThree: 'Perfect for gifting or home decor.',
    },
    productDimensions: {
      height: '50 cm',
      weight: '1.5 kg',
      depth: '25 cm',
    },
  },
  {
    id: 8,
    name: 'Plant Eucal',
    slug: 'Plant-Eucal',
    brand: 'Plant Paradise',
    productImage:'Plants/plantEight.webp',
    productTitle: 'Charming Potted Cactus',
    productPrice: 15.99,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 20,
    ratings: 4.0,
    tags: ['Outdoor', 'Succulent'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.2,
        height: 0.4,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'A low-maintenance option for any space.',
      descOne: 'Thrives on neglect and loves sunny spots.',
      descTwo: 'Perfect for those who travel often.',
      descThree: 'Adds a unique touch to your decor.',
    },
    productDimensions: {
      height: '25 cm',
      weight: '0.5 kg',
      depth: '20 cm',
    },
  },
  {
    id: 9,
    name: 'Plant Snade',
    slug: 'Plant-Snade',
    brand: 'Green Haven',
    productImage:'Plants/plant9.webp',
    productTitle: 'Vibrant Green Snade',
    productPrice: 19.99,

    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 15,
    ratings: 4.2,
    tags: ['Indoor', 'Outdoor'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.4,
        height: 0.8,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'Brings a lush green touch to your home.',
      descOne: 'Prefers indirect sunlight and consistent moisture.',
      descTwo: 'A great air purifier for indoor spaces.',
      descThree: 'Perfect for any room in your home.',
    },
    productDimensions: {
      height: '60 cm',
      weight: '2 kg',
      depth: '30 cm',
    },
  },
  {
    id: 10,
    name: 'Plant Rose',
    slug: 'Plant-Rose',
    brand: 'Flora Boutique',
    productImage:'Plants/plantTen.webp',
    productTitle: 'Stunning Flowering Plant',
    productPrice: 35.99,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 8,
    ratings: 4.5,
    tags: ['Flowering', 'Indoor'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.3,
        height: 0.5,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A beautiful flowering plant that brightens any space.',
      descOne: 'Requires moderate sunlight and regular watering.',
      descTwo: 'Perfect for gifting and special occasions.',
      descThree: 'Adds color and charm to your decor.',
    },
    productDimensions: {
      height: '45 cm',
      weight: '1.5 kg',
      depth: '25 cm',
    },
  },
  {
    id: 11,
    name: 'Plant Abelia',
    slug: 'Plant-Abelia',
    brand: 'Green Haven',
    productImage:'Plants/plantEleven.webp',
    productTitle: 'Elegant Abelia Plant',
    productPrice: 29.99,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: true,
    stock: 10,
    ratings: 4.0,
    tags: ['Indoor', 'Low Light'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.4,
        height: 0.7,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'A stunning fern that thrives indoors.',
      descOne: 'Requires minimal care and attention.',
      descTwo: 'Perfect for improving indoor air quality.',
      descThree: 'An attractive addition to any home.',
    },
    productDimensions: {
      height: '50 cm',
      weight: '1 kg',
      depth: '30 cm',
    },
  },
  {
    id: 12,
    name: 'Plant AfricanMilk',
    slug: 'Plant-AfricanMilk',
    brand: 'Plant Paradise',
    productImage:'Plants/plantTwelve.webp',
    productTitle: 'Charming Potted AfricanMilk',
    productPrice: 22.5,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 25,
    ratings: 4.5,
    tags: ['Outdoor', 'Succulent'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.5,
        height: 0.4,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A low-maintenance plant perfect for outdoor spaces.',
      descOne: 'Thrives on neglect and loves sunny spots.',
      descTwo: 'Adds a unique touch to your garden.',
      descThree: 'Perfect for decorative purposes.',
    },
    productDimensions: {
      height: '30 cm',
      weight: '0.5 kg',
      depth: '20 cm',
    },
  },
  {
    id: 13,
    name: 'Plant AfricanSpear',
    slug: 'Plant-AfricanSpear',
    brand: 'Flora Boutique',
    productImage:'Plants/plantThirteen.webp',
    productTitle: 'Stunning Flowering Plant',
    productPrice: 45.0,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 15,
    ratings: 4.3,
    tags: ['Indoor', 'Flowering'],
    shipping: {
      weight: 1.5,
      dimensions: {
        width: 0.3,
        height: 0.5,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Requires moderate sunlight and regular watering.',
      descTwo: 'Perfect for gifting and special occasions.',
      descThree: 'Adds color and charm to your decor.',
    },
    productDimensions: {
      height: '40 cm',
      weight: '1.2 kg',
      depth: '25 cm',
    },
  },
  {
    id: 14,
    name: 'Plant Agapanthus',
    slug: 'Plant-Agapanthus',
    brand: 'Green Haven',
    productImage:'Plants/plantFourteen.webp',
    productTitle: 'Elegant Fern Plant',
    productPrice: 29.99,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 20,
    ratings: 4.0,
    tags: ['Indoor', 'Low Light'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.4,
        height: 0.7,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'A stunning fern that thrives indoors.',
      descOne: 'Requires minimal care and attention.',
      descTwo: 'Perfect for improving indoor air quality.',
      descThree: 'An attractive addition to any home.',
    },
    productDimensions: {
      height: '50 cm',
      weight: '1 kg',
      depth: '30 cm',
    },
  },
  {
    id: 15,
    name: 'Plant AfricanIris',
    slug: 'Plant-AfricanIris',
    brand: 'Plant Paradise',
    productImage:'Plants/plantFifteen.webp',
    productTitle: 'Charming Potted AfricanIris',
    productPrice: 22.5,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 25,
    ratings: 4.5,
    tags: ['Outdoor', 'Succulent'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.5,
        height: 0.4,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A low-maintenance plant perfect for outdoor spaces.',
      descOne: 'Thrives on neglect and loves sunny spots.',
      descTwo: 'Adds a unique touch to your garden.',
      descThree: 'Perfect for decorative purposes.',
    },
    productDimensions: {
      height: '30 cm',
      weight: '0.5 kg',
      depth: '20 cm',
    },
  },
  {
    id: 16,
    name: 'Plant Acoma',
    slug: 'Plant-Acoma',
    brand: 'Flora Boutique',
    productImage:'Plants/plantSixteen.webp',
    productTitle: 'Beautiful Indoor Plant',
    productPrice: 86.67,
    category: 'plants',
    material: 'Wood',
    isAvailable: false,
    stock: 42,
    ratings: 1.6,
    tags: ['Low Light'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.26,
        height: 0.81,
        depth: 0.26,
      },
    },
    productDescription: {
      main: 'A unique and vibrant centerpiece for your decor.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Perfect for any room in your home.',
      descThree: 'Brings a splash of color to your home.',
    },
    productDimensions: {
      height: '21 cm',
      weight: '4 kg',
      depth: '55 cm',
    },
  },
  {
    id: 17,
    name: 'Plant Agastache',
    slug: 'Plant-Agastache',
    brand: 'Flora Boutique',
    productImage:'Plants/plantSeventeen.webp',
    productTitle: 'Vibrant Green Agastache',
    productPrice: 65.87,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 36,
    ratings: 3.8,
    tags: ['Outdoor'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.49,
        height: 0.49,
        depth: 0.38,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'An attractive addition to any home.',
    },
    productDimensions: {
      height: '28 cm',
      weight: '5 kg',
      depth: '35 cm',
    },
  },
  {
    id: 18,
    name: 'Plant Daisy',
    slug: 'Plant-Daisy',
    brand: 'Flora Boutique',
    productImage:'Plants/plantEighteen.webp',
    productTitle: 'Charming Potted Daisy',
    productPrice: 45.99,
    category: 'plants',
    material: 'Wood',
    isAvailable: false,
    stock: 18,
    ratings: 4.4,
    tags: ['Indoor', 'Succulent'],
    shipping: {
      weight: 7,
      dimensions: {
        width: 0.3,
        height: 0.3,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'Adds a unique touch to your garden.',
      descOne: 'Perfect for those who travel often.',
      descTwo: 'Thrives on neglect and loves sunny spots.',
      descThree: 'Ideal for beginners and experts alike.',
    },
    productDimensions: {
      height: '25 cm',
      weight: '1 kg',
      depth: '20 cm',
    },
  },
  {
    id: 19,
    name: 'Plant Raby Bubber',
    slug: 'Plant-Raby-Bubber',
    brand: 'Green Haven',
    productImage:'Plants/plantNineteen.webp',
    productTitle: 'Elegant Rose Plant',
    productPrice: 35.0,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 12,
    ratings: 3.0,
    tags: ['Indoor'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.2,
        height: 0.4,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'Perfect for adding a splash of color indoors.',
      descOne: 'Requires moderate sunlight and regular watering.',
      descTwo: 'Ideal for gifting or personal use.',
      descThree: 'Adds charm and beauty to your decor.',
    },
    productDimensions: {
      height: '30 cm',
      weight: '1 kg',
      depth: '20 cm',
    },
  },
  {
    id: 20,
    name: 'Plant Ballon Flower',
    slug: 'Plant-Ballon-Flower',
    brand: 'Flora Boutique',
    productImage:'Plants/plantTwenty.webp',
    productTitle: 'Vibrant Green Ballon Flower',
    productPrice: 22.5,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 30,
    ratings: 4.2,
    tags: ['Indoor', 'Outdoor'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.5,
        height: 0.6,
        depth: 0.5,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Enhances indoor air quality.',
      descTwo: 'Requires minimal care and attention.',
      descThree: 'Perfect for any room in your home.',
    },
    productDimensions: {
      height: '45 cm',
      weight: '1 kg',
      depth: '30 cm',
    },
  },
  {
    id: 21,
    name: 'Plant Cactus',
    slug: 'Plant-Cactus',
    brand: 'Plant Paradise',
    productImage:'Plants/plantTwentyOne.webp',
    productTitle: 'Charming Potted Cactus',
    productPrice: 35.99,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 5,
    ratings: 4.3,
    tags: ['Outdoor', 'Succulent'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.3,
        height: 0.4,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A low-maintenance option for any space.',
      descOne: 'Thrives on neglect and loves sunny spots.',
      descTwo: 'Adds a unique touch to your garden.',
      descThree: 'Perfect for decorative purposes.',
    },
    productDimensions: {
      height: '25 cm',
      weight: '0.5 kg',
      depth: '20 cm',
    },
  },
  {
    id: 22,
    name: 'Plant BachelorRose',
    slug: 'Plant-BachelorRose',
    brand: 'Green Haven',
    productImage:'Plants/plantTwentyTwo.webp',
    productTitle: 'Elegant BachelorRose',
    productPrice: 25.5,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 8,
    ratings: 3.5,
    tags: ['Indoor'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.3,
        height: 0.4,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'Perfect for adding a splash of color indoors.',
      descOne: 'Requires moderate sunlight and regular watering.',
      descTwo: 'Ideal for gifting or personal use.',
      descThree: 'Adds charm and beauty to your decor.',
    },
    productDimensions: {
      height: '30 cm',
      weight: '1 kg',
      depth: '20 cm',
    },
  },
  {
    id: 23,
    name: 'Plant Caletha',
    slug: 'Plant-Caletha',
    brand: 'Flora Boutique',
    productImage:'Plants/plantTwentyThree.webp',
    productTitle: 'Vibrant Green Fern',
    productPrice: 19.99,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: true,
    stock: 15,
    ratings: 4.0,
    tags: ['Indoor', 'Outdoor'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.4,
        height: 0.8,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'Brings a lush green touch to your home.',
      descOne: 'Prefers indirect sunlight and consistent moisture.',
      descTwo: 'A great air purifier for indoor spaces.',
      descThree: 'Perfect for any room in your home.',
    },
    productDimensions: {
      height: '60 cm',
      weight: '2 kg',
      depth: '30 cm',
    },
  },
  {
    id: 24,
    name: 'Plant Cabagge',
    slug: 'Plant-Cabagge',
    brand: 'Plant Paradise',
    productImage:'Plants/plantTwentyFour.webp',
    productTitle: 'Charming Potted Cabagge',
    productPrice: 22.5,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 25,
    ratings: 4.5,
    tags: ['Outdoor', 'Succulent'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.5,
        height: 0.4,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A low-maintenance plant perfect for outdoor spaces.',
      descOne: 'Thrives on neglect and loves sunny spots.',
      descTwo: 'Adds a unique touch to your garden.',
      descThree: 'Perfect for decorative purposes.',
    },
    productDimensions: {
      height: '30 cm',
      weight: '0.5 kg',
      depth: '20 cm',
    },
  },
  {
    id: 25,
    name: 'Plant Caladium',
    slug: 'Plant-Caladium',
    brand: 'Flora Boutique',
    productImage:'Plants/plantTwentyFive.webp',
    productTitle: 'Beautiful Indoor Plant',
    productPrice: 86.67,
    category: 'plants',
    material: 'Wood',
    isAvailable: false,
    stock: 42,
    ratings: 1.6,
    tags: ['Low Light'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.26,
        height: 0.81,
        depth: 0.26,
      },
    },
    productDescription: {
      main: 'A unique and vibrant centerpiece for your decor.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Perfect for any room in your home.',
      descThree: 'Brings a splash of color to your home.',
    },
    productDimensions: {
      height: '21 cm',
      weight: '4 kg',
      depth: '55 cm',
    },
  },
  {
    id: 26,
    name: 'Plant Calateha',
    slug: 'Plant-Calateha',
    brand: 'Flora Boutique',
    productImage:'Plants/plantTwentySix.webp',
    productTitle: 'Vibrant Green Calateha',
    productPrice: 65.87,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 36,
    ratings: 3.8,
    tags: ['Outdoor'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.49,
        height: 0.49,
        depth: 0.38,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'An attractive addition to any home.',
    },
    productDimensions: {
      height: '28 cm',
      weight: '5 kg',
      depth: '35 cm',
    },
  },
  {
    id: 27,
    name: 'Plant Murdyk',
    slug: 'Plant-Murdyk',
    brand: 'Flora Boutique',
    productImage:'Plants/plantTwentySeven.webp',
    productTitle: 'Charming Potted Murdyk',
    productPrice: 15.99,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 20,
    ratings: 4.0,
    tags: ['Outdoor', 'Succulent'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.2,
        height: 0.4,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'A low-maintenance option for any space.',
      descOne: 'Thrives on neglect and loves sunny spots.',
      descTwo: 'Perfect for those who travel often.',
      descThree: 'Adds a unique touch to your decor.',
    },
    productDimensions: {
      height: '25 cm',
      weight: '0.5 kg',
      depth: '20 cm',
    },
  },
  {
    id: 28,
    name: 'Plant Miadol',
    slug: 'Plant-Miadol',
    brand: 'Plant Paradise',
    productImage:'Plants/plantTwentyEight.webp',
    productTitle: 'Elegant Fern Miadol',
    productPrice: 29.99,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 15,
    ratings: 4.2,
    tags: ['Indoor', 'Outdoor'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.4,
        height: 0.8,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'A stunning fern that thrives indoors.',
      descOne: 'Requires minimal care and attention.',
      descTwo: 'Perfect for improving indoor air quality.',
      descThree: 'An attractive addition to any home.',
    },
    productDimensions: {
      height: '60 cm',
      weight: '2 kg',
      depth: '30 cm',
    },
  },
  {
    id: 29,
    name: 'Plant Oliver',
    slug: 'Plant-Oliver',
    brand: 'Green Haven',
    productImage:'Plants/plantTwentyNine.webp',
    productTitle: 'Charming Potted Oliver',
    productPrice: 22.5,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 5,
    ratings: 4.5,
    tags: ['Outdoor', 'Succulent'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.5,
        height: 0.4,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A low-maintenance option for any space.',
      descOne: 'Thrives on neglect and loves sunny spots.',
      descTwo: 'Adds a unique touch to your garden.',
      descThree: 'Perfect for decorative purposes.',
    },
    productDimensions: {
      height: '30 cm',
      weight: '0.5 kg',
      depth: '20 cm',
    },
  },
  {
    id: 30,
    name: 'Plant Cacoon',
    slug: 'Plant-Cacoon',
    brand: 'Flora Boutique',
    productImage:'Plants/plantThirty.webp',
    productTitle: 'Beautiful Indoor Cacoon Plant',
    productPrice: 86.67,
    category: 'plants',
    material: 'Wood',
    isAvailable: false,
    stock: 42,
    ratings: 1.6,
    tags: ['Low Light'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.26,
        height: 0.81,
        depth: 0.26,
      },
    },
    productDescription: {
      main: 'A unique and vibrant centerpiece for your decor.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Perfect for any room in your home.',
      descThree: 'Brings a splash of color to your home.',
    },
    productDimensions: {
      height: '21 cm',
      weight: '4 kg',
      depth: '55 cm',
    },
  },
  {
    id: 31,
    name: 'Plant Fusion',
    slug: 'Plant-Fusion',
    brand: 'Flora Boutique',
    productImage:'Plants/plantThirtyOne.webp',
    productTitle: 'Vibrant Green Fusion',
    productPrice: 65.87,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 36,
    ratings: 3.8,
    tags: ['Outdoor'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.49,
        height: 0.49,
        depth: 0.38,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'An attractive addition to any home.',
    },
    productDimensions: {
      height: '28 cm',
      weight: '5 kg',
      depth: '35 cm',
    },
  },
  {
    id: 32,
    name: 'Plant Oribifolia',
    slug: 'Plant-Oribifolia',
    brand: 'Plant Paradise',
    productImage:'Plants/plantThirtyTwo.webp',
    productTitle: 'Charming Potted Oribifolia',
    productPrice: 15.99,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 20,
    ratings: 4.0,
    tags: ['Outdoor', 'Succulent'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.2,
        height: 0.4,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'A low-maintenance option for any space.',
      descOne: 'Thrives on neglect and loves sunny spots.',
      descTwo: 'Perfect for those who travel often.',
      descThree: 'Adds a unique touch to your decor.',
    },
    productDimensions: {
      height: '25 cm',
      weight: '0.5 kg',
      depth: '20 cm',
    },
  },
  {
    id: 33,
    name: 'Plant Makden',
    slug: 'Plant-Makden',
    brand: 'Green Haven',
    productImage:'Plants/plantThirtyThree.webp',
    productTitle: 'Elegant Makden Plant',
    productPrice: 35.0,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 12,
    ratings: 3.0,
    tags: ['Indoor'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.2,
        height: 0.4,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'Perfect for adding a splash of color indoors.',
      descOne: 'Requires moderate sunlight and regular watering.',
      descTwo: 'Ideal for gifting or personal use.',
      descThree: 'Adds charm and beauty to your decor.',
    },
    productDimensions: {
      height: '30 cm',
      weight: '1 kg',
      depth: '20 cm',
    },
  },
  {
    id: 34,
    name: 'Plant Mystoc',
    slug: 'Plant-Mystoc',
    brand: 'Flora Boutique',
    productImage:'Plants/plantThirtyFour.webp',
    productTitle: 'Vibrant Green Mystoc',
    productPrice: 22.5,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 15,
    ratings: 4.2,
    tags: ['Indoor', 'Outdoor'],
    shipping: {
      weight: 2,
      dimensions: {
        width: 0.4,
        height: 0.8,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'Brings a lush green touch to your home.',
      descOne: 'Prefers indirect sunlight and consistent moisture.',
      descTwo: 'A great air purifier for indoor spaces.',
      descThree: 'Perfect for any room in your home.',
    },
    productDimensions: {
      height: '60 cm',
      weight: '2 kg',
      depth: '30 cm',
    },
  },
  {
    id: 35,
    name: 'Plant Mizz',
    slug: 'Plant-Mizz',
    brand: 'Plant Paradise',
    productImage:'Plants/plantThirtyFive.webp',
    productTitle: 'Charming Potted Mizz',
    productPrice: 35.99,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 8,
    ratings: 4.5,
    tags: ['Outdoor', 'Succulent'],
    shipping: {
      weight: 1.5,
      dimensions: {
        width: 0.2,
        height: 0.4,
        depth: 0.2,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Requires moderate sunlight and regular watering.',
      descTwo: 'Perfect for gifting and special occasions.',
      descThree: 'Adds color and charm to your decor.',
    },
    productDimensions: {
      height: '45 cm',
      weight: '1.2 kg',
      depth: '25 cm',
    },
  },
  {
    id: 36,
    name: 'Plant Numera',
    slug: 'Plant-Numera',
    brand: 'Green Haven',
    productImage:'Plants/plantThirtySix.webp',
    productTitle: 'Beautiful Indoor Numera Plant',
    productPrice: 55.0,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 10,
    ratings: 4.7,
    tags: ['Flowering', 'Indoor'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.3,
        height: 0.4,
        depth: 0.3,
      },
    },
    productDescription: {
      main: 'A unique and vibrant centerpiece for your decor.',
      descOne: 'Requires indirect sunlight and moderate watering.',
      descTwo: 'Perfect for gifting or home decor.',
      descThree: 'Brings a splash of color to your home.',
    },
    productDimensions: {
      height: '30 cm',
      weight: '1 kg',
      depth: '20 cm',
    },
  },
  {
    id: 37,
    name: 'Plant Rivera',
    slug: 'Plant-Rivera',
    brand: 'Flora Boutique',
    productImage:'Plants/plantThirtySeven.webp',
    productTitle: 'Beautiful Indoor Rivera Plant',
    productPrice: 86.67,
    category: 'plants',
    material: 'Wood',
    isAvailable: false,
    stock: 42,
    ratings: 1.6,
    tags: ['Low Light'],
    shipping: {
      weight: 5,
      dimensions: {
        width: 0.26,
        height: 0.81,
        depth: 0.26,
      },
    },
    productDescription: {
      main: 'A unique and vibrant centerpiece for your decor.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Perfect for any room in your home.',
      descThree: 'Brings a splash of color to your home.',
    },
    productDimensions: {
      height: '21 cm',
      weight: '4 kg',
      depth: '55 cm',
    },
  },
  {
    id: 38,
    name: 'Plant Clits',
    slug: 'Plant-Clits',
    brand: 'Flora Boutique',
    productImage:'Plants/plantThirtyEight.webp',
    productTitle: 'Vibrant Clits Fern',
    productPrice: 65.87,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 36,
    ratings: 3.8,
    tags: ['Outdoor'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.49,
        height: 0.49,
        depth: 0.38,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'An attractive addition to any home.',
    },
    productDimensions: {
      height: '28 cm',
      weight: '5 kg',
      depth: '35 cm',
    },
  },
  {
    id: 39,
    name: 'Plant Atik',
    slug: 'Plant-Atik',
    brand: 'Flora Boutique',
    productImage:'Plants/plantThirtyNine.webp',
    productTitle: 'Stunning Flowering Plant',
    productPrice: 35.8,
    category: 'plants',
    material: 'Wood',
    isAvailable: false,
    stock: 47,
    ratings: 3.4,
    tags: ['Air Purifying', 'Low Light', 'Outdoor'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.24,
        height: 0.46,
        depth: 0.35,
      },
    },
    productDescription: {
      main: 'A unique and vibrant centerpiece for your decor.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Thrives in various environments.',
      descThree: 'This plant will flourish with minimal care.',
    },
    productDimensions: {
      height: '43 cm',
      weight: '2 kg',
      depth: '34 cm',
    },
  },
  {
    id: 40,
    name: 'Plant Chents',
    slug: 'Plant-Chents',
    brand: 'Green Haven',
    productImage:'Plants/plantForty.webp',
    productTitle: 'Stunning Flowering Chents Plant',
    productPrice: 60.8,
    category: 'plants',
    material: 'Plastic',
    isAvailable: false,
    stock: 48,
    ratings: 0.2,
    tags: ['Indoor', 'Air Purifying', 'Succulent'],
    shipping: {
      weight: 9,
      dimensions: {
        width: 0.26,
        height: 0.61,
        depth: 0.6,
      },
    },
    productDescription: {
      main: 'A perfect plant for indoor and outdoor spaces.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Thrives in various environments.',
      descThree: 'A delightful addition to your garden.',
    },
    productDimensions: {
      height: '46 cm',
      weight: '1 kg',
      depth: '31 cm',
    },
  },
  {
    id: 41,
    name: 'Plant Tatel',
    slug: 'Plant-Tatel',
    brand: 'Flora Boutique',
    productImage:'Plants/plantFortyOne.webp',
    productTitle: 'Charming Potted Tatel',
    productPrice: 92.39,
    category: 'plants',
    material: 'Wood',
    isAvailable: false,
    stock: 18,
    ratings: 3.7,
    tags: ['Indoor', 'Succulent'],
    shipping: {
      weight: 7,
      dimensions: {
        width: 0.9,
        height: 1.15,
        depth: 0.34,
      },
    },
    productDescription: {
      main: 'A perfect plant for indoor and outdoor spaces.',
      descOne: 'Grows well in low light conditions.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'Adapts easily to its surroundings.',
    },
    productDimensions: {
      height: '27 cm',
      weight: '4 kg',
      depth: '28 cm',
    },
  },
  {
    id: 42,
    name: 'Plant Akumer',
    slug: 'Plant-Akumer',
    brand: 'Flora Boutique',
    productImage:'Plants/plantFortyTwo.webp',
    productTitle: 'Stunning Flowering Plant',
    productPrice: 55.88,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: false,
    stock: 14,
    ratings: 4.4,
    tags: ['Succulent', 'Indoor', 'Flowering'],
    shipping: {
      weight: 9,
      dimensions: {
        width: 0.31,
        height: 1.46,
        depth: 0.48,
      },
    },
    productDescription: {
      main: 'A unique and vibrant centerpiece for your decor.',
      descOne: 'Provides excellent air purification.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'Adapts easily to its surroundings.',
    },
    productDimensions: {
      height: '30 cm',
      weight: '3 kg',
      depth: '43 cm',
    },
  },
  {
    id: 43,
    name: 'Plant Fetics',
    slug: 'Plant-Fetics',
    brand: 'Flora Boutique',
    productImage:'Plants/plantFortyThree.webp',
    productTitle: 'Vibrant Green Fetics',
    productPrice: 54.38,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: false,
    stock: 32,
    ratings: 1.9,
    tags: ['Flowering', 'Air Purifying'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.5,
        height: 0.55,
        depth: 0.43,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'Ideal for beginners and experts alike.',
    },
    productDimensions: {
      height: '35 cm',
      weight: '1 kg',
      depth: '56 cm',
    },
  },
  {
    id: 44,
    name: 'Plant Aribta',
    slug: 'Plant-Aribta',
    brand: 'Plant Paradise',
    productImage:'Plants/plantFortyFour.webp',
    productTitle: 'Vibrant Green Aribta',
    productPrice: 85.93,
    category: 'plants',
    material: 'Wood',
    isAvailable: false,
    stock: 31,
    ratings: 4.2,
    tags: ['Flowering', 'Air Purifying', 'Succulent'],
    shipping: {
      weight: 4,
      dimensions: {
        width: 0.61,
        height: 1.06,
        depth: 0.66,
      },
    },
    productDescription: {
      main: 'A unique and vibrant centerpiece for your decor.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Thrives in various environments.',
      descThree: 'This plant will flourish with minimal care.',
    },
    productDimensions: {
      height: '63 cm',
      weight: '3 kg',
      depth: '29 cm',
    },
  },
  {
    id: 45,
    name: 'Plant Systol',
    slug: 'Plant-Systol',
    brand: 'Plant Paradise',
    productImage:'Plants/plantFortyFive.webp',
    productTitle: 'Beautiful Systol Plant',
    productPrice: 23.45,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 35,
    ratings: 4.3,
    tags: ['Air Purifying'],
    shipping: {
      weight: 9,
      dimensions: {
        width: 0.31,
        height: 1.05,
        depth: 0.63,
      },
    },
    productDescription: {
      main: 'A unique and vibrant centerpiece for your decor.',
      descOne: 'Grows well in low light conditions.',
      descTwo: 'Enhances indoor air quality.',
      descThree: 'This plant will flourish with minimal care.',
    },
    productDimensions: {
      height: '58 cm',
      weight: '4 kg',
      depth: '57 cm',
    },
  },
  {
    id: 46,
    name: 'Plant Dahlia',
    slug: 'Plant-Dahlia',
    brand: 'Green Haven',
    productImage:'Plants/plantFortySix.webp',
    productTitle: 'Beautiful Indoor Dahlia Plant',
    productPrice: 17.83,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: false,
    stock: 17,
    ratings: 2.3,
    tags: ['Indoor'],
    shipping: {
      weight: 9,
      dimensions: {
        width: 0.92,
        height: 0.77,
        depth: 0.76,
      },
    },
    productDescription: {
      main: 'Easy to care for and perfect for beginners.',
      descOne: 'Provides excellent air purification.',
      descTwo: 'Perfect for any room in your home.',
      descThree: 'Brings a splash of color to your home.',
    },
    productDimensions: {
      height: '49 cm',
      weight: '3 kg',
      depth: '33 cm',
    },
  },
  {
    id: 47,
    name: 'Plant Setetrial',
    slug: 'Plant-Setetrial',
    brand: 'Flora Boutique',
    productImage:'Plants/plantFortySeven.webp',
    productTitle: 'Beautiful Indoor Setetrial Plant',
    productPrice: 77.92,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 2,
    ratings: 2.0,
    tags: ['Succulent'],
    shipping: {
      weight: 10,
      dimensions: {
        width: 0.64,
        height: 0.95,
        depth: 0.73,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Grows well in low light conditions.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'Ideal for beginners and experts alike.',
    },
    productDimensions: {
      height: '61 cm',
      weight: '4 kg',
      depth: '33 cm',
    },
  },
  {
    id: 48,
    name: 'Plant DatePalm',
    slug: 'Plant-DatePalm',
    brand: 'Green Haven',
    productImage:'Plants/plantFortyEight.webp',
    productTitle: 'Vibrant DatePalm Fern',
    productPrice: 99.09,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: false,
    stock: 9,
    ratings: 1.2,
    tags: ['Low Light', 'Flowering', 'Outdoor'],
    shipping: {
      weight: 10,
      dimensions: {
        width: 0.9,
        height: 1.1,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'A perfect plant for indoor and outdoor spaces.',
      descOne: 'Provides excellent air purification.',
      descTwo: 'Enhances indoor air quality.',
      descThree: 'A delightful addition to your garden.',
    },
    productDimensions: {
      height: '49 cm',
      weight: '3 kg',
      depth: '47 cm',
    },
  },
  {
    id: 49,
    name: 'Plant RedWood',
    slug: 'Plant-RedWood',
    brand: 'Flora Boutique',
    productImage:'Plants/plantFortyNine.webp',
    productTitle: 'Elegant RedWood Succulent',
    productPrice: 22.17,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 6,
    ratings: 3.6,
    tags: ['Succulent', 'Flowering', 'Outdoor'],
    shipping: {
      weight: 3,
      dimensions: {
        width: 0.43,
        height: 0.45,
        depth: 0.7,
      },
    },
    productDescription: {
      main: 'Easy to care for and perfect for beginners.',
      descOne: 'Provides excellent air purification.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'Brings a splash of color to your home.',
    },
    productDimensions: {
      height: '29 cm',
      weight: '4 kg',
      depth: '49 cm',
    },
  },
  {
    id: 50,
    name: 'Plant Delphinium',
    slug: 'Plant-Delphinium',
    brand: 'Flora Boutique',
    productImage:'Plants/plantFifty.webp',
    productTitle: 'Vibrant Delphinium Fern',
    productPrice: 41.46,
    category: 'plants',
    material: 'Plastic',
    isAvailable: false,
    stock: 20,
    ratings: 3.0,
    tags: ['Flowering', 'Outdoor'],
    shipping: {
      weight: 8,
      dimensions: {
        width: 0.74,
        height: 0.72,
        depth: 0.55,
      },
    },
    productDescription: {
      main: 'A perfect plant for indoor and outdoor spaces.',
      descOne: 'Attracts butterflies and other pollinators.',
      descTwo: 'Thrives in various environments.',
      descThree: 'Ideal for beginners and experts alike.',
    },
    productDimensions: {
      height: '76 cm',
      weight: '5 kg',
      depth: '23 cm',
    },
  },

  {
    id: 51,
    name: 'Plant Daphne',
    slug: 'Plant-Daphne',
    brand: 'Plant Paradise',
    productImage:'Plants/plantFiftyOne.webp',
    productTitle: 'Stunning Flowering Daphne Plant',
    productPrice: 96.43,
    category: 'plants',
    material: 'Wood',
    isAvailable: false,
    stock: 38,
    ratings: 2.2,
    tags: ['Flowering'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.58,
        height: 0.81,
        depth: 0.36,
      },
    },
    productDescription: {
      main: 'Easy to care for and perfect for beginners.',
      descOne: 'Attracts butterflies and other pollinators.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'Adapts easily to its surroundings.',
    },
    productDimensions: {
      height: '39 cm',
      weight: '2 kg',
      depth: '38 cm',
    },
  },
  {
    id: 52,
    name: 'Plant EarlyHaverst',
    slug: 'Plant-EarlyHaverst',
    brand: 'Plant Paradise',
    productImage:'Plants/plantFiftyTwo.webp',
    productTitle: 'Vibrant EarlyHaverst Fern',
    productPrice: 34.95,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: true,
    stock: 19,
    ratings: 0.2,
    tags: ['Low Light', 'Succulent', 'Air Purifying'],
    shipping: {
      weight: 8,
      dimensions: {
        width: 0.7,
        height: 0.7,
        depth: 0.38,
      },
    },
    productDescription: {
      main: 'Easy to care for and perfect for beginners.',
      descOne: 'Comes in a beautiful decorative pot.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'Ideal for beginners and experts alike.',
    },
    productDimensions: {
      height: '74 cm',
      weight: '1 kg',
      depth: '43 cm',
    },
  },
  {
    id: 53,
    name: 'Plant Easter',
    slug: 'Plant-Easter',
    brand: 'Green Haven',
    productImage:'Plants/plantFiftyThree.webp',
    productTitle: 'Charming Potted Easter',
    productPrice: 86.37,
    category: 'plants',
    material: 'Plastic',
    isAvailable: true,
    stock: 2,
    ratings: 4.8,
    tags: ['Flowering', 'Indoor'],
    shipping: {
      weight: 7,
      dimensions: {
        width: 0.95,
        height: 0.41,
        depth: 0.59,
      },
    },
    productDescription: {
      main: 'A unique and vibrant centerpiece for your decor.',
      descOne: 'Attracts butterflies and other pollinators.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'A delightful addition to your garden.',
    },
    productDimensions: {
      height: '56 cm',
      weight: '3 kg',
      depth: '20 cm',
    },
  },
  {
    id: 54,
    name: 'Plant Welder',
    slug: 'Plant-Welder',
    brand: 'Green Haven',
    productImage:'Plants/plantFiftyFour.webp',
    productTitle: 'Charming Potted Welder',
    productPrice: 27.31,
    category: 'plants',
    material: 'Wood',
    isAvailable: false,
    stock: 28,
    ratings: 2.3,
    tags: ['Flowering', 'Succulent', 'Outdoor'],
    shipping: {
      weight: 8,
      dimensions: {
        width: 0.98,
        height: 0.9,
        depth: 0.4,
      },
    },
    productDescription: {
      main: 'A perfect plant for indoor and outdoor spaces.',
      descOne: 'Comes in a beautiful decorative pot.',
      descTwo: 'Perfect for any room in your home.',
      descThree: 'Ideal for beginners and experts alike.',
    },
    productDimensions: {
      height: '79 cm',
      weight: '3 kg',
      depth: '20 cm',
    },
  },
  {
    id: 55,
    name: 'Plant Fitaj',
    slug: 'Plant-Fitaj',
    brand: 'Flora Boutique',
    productImage:'Plants/plantFiftyFive.webp',
    productTitle: 'Elegant Fitaj Succulent',
    productPrice: 97.05,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 9,
    ratings: 4.8,
    tags: ['Indoor'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.82,
        height: 0.71,
        depth: 0.29,
      },
    },
    productDescription: {
      main: 'Adds a touch of nature to your surroundings.',
      descOne: 'Comes in a beautiful decorative pot.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'Ideal for beginners and experts alike.',
    },
    productDimensions: {
      height: '50 cm',
      weight: '1 kg',
      depth: '50 cm',
    },
  },
  {
    id: 56,
    name: 'Plant Ateled',
    slug: 'Plant-Ateled',
    brand: 'Plant Paradise',
    productImage:'Plants/plantFiftySix.webp',
    productTitle: 'Elegant Ateled Succulent',
    productPrice: 28.03,
    category: 'plants',
    material: 'Plastic',
    isAvailable: false,
    stock: 39,
    ratings: 4.0,
    tags: ['Low Light', 'Indoor'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.56,
        height: 0.92,
        depth: 0.39,
      },
    },
    productDescription: {
      main: 'A unique and vibrant centerpiece for your decor.',
      descOne: 'Attracts butterflies and other pollinators.',
      descTwo: 'Enhances indoor air quality.',
      descThree: 'This plant will flourish with minimal care.',
    },
    productDimensions: {
      height: '80 cm',
      weight: '4 kg',
      depth: '25 cm',
    },
  },
  {
    id: 57,
    name: 'Plant Tomato Wavy',
    slug: 'Plant-Tomato-Wavy',
    brand: 'Plant Paradise',
    productImage:'Plants/plantFiftySeven.webp',
    productTitle: 'Vibrant Tomato Wavy Fern',
    productPrice: 15.31,
    category: 'plants',
    material: 'Wood',
    isAvailable: true,
    stock: 35,
    ratings: 3.5,
    tags: ['Outdoor', 'Low Light', 'Indoor'],
    shipping: {
      weight: 7,
      dimensions: {
        width: 0.83,
        height: 0.84,
        depth: 0.71,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Attracts butterflies and other pollinators.',
      descTwo: 'A great way to brighten up any space.',
      descThree: 'Adapts easily to its surroundings.',
    },
    productDimensions: {
      height: '50 cm',
      weight: '2 kg',
      depth: '36 cm',
    },
  },
  {
    id: 58,
    name: 'Plant Hemlock',
    slug: 'Plant-Hemlock',
    brand: 'Green Haven',
    productImage:'Plants/plantFiftyEight.webp',
    productTitle: 'Charming Potted Cactus',
    productPrice: 86.96,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: false,
    stock: 36,
    ratings: 3.9,
    tags: ['Indoor', 'Outdoor'],
    shipping: {
      weight: 10,
      dimensions: {
        width: 0.53,
        height: 0.65,
        depth: 0.24,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Comes in a beautiful decorative pot.',
      descTwo: 'Thrives in various environments.',
      descThree: 'Adapts easily to its surroundings.',
    },
    productDimensions: {
      height: '69 cm',
      weight: '1 kg',
      depth: '44 cm',
    },
  },
  {
    id: 59,
    name: 'Plant Adimer',
    slug: 'Plant-Adimer',
    brand: 'Flora Boutique',
    productImage:'Plants/plantFiftyNine.webp',
    productTitle: 'Vibrant Adimer Ert',
    productPrice: 54.38,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: false,
    stock: 32,
    ratings: 1.9,
    tags: ['Flowering', 'Air Purifying'],
    shipping: {
      weight: 6,
      dimensions: {
        width: 0.5,
        height: 0.55,
        depth: 0.43,
      },
    },
    productDescription: {
      main: 'A beautiful addition to any home or office.',
      descOne: 'Low maintenance and drought-resistant.',
      descTwo: 'Ideal gift for plant lovers.',
      descThree: 'Ideal for beginners and experts alike.',
    },
    productDimensions: {
      height: '35 cm',
      weight: '1 kg',
      depth: '56 cm',
    },
  },

  {
    id: 60,
    name: 'Plant Estel',
    slug: 'Plant-Estel',
    brand: 'Flora Boutique',
    productImage:'Plants/plantSixty.webp',
    productTitle: 'Charming Potted Estel',
    productPrice: 68.06,
    category: 'plants',
    material: 'Ceramic',
    isAvailable: false,
    stock: 46,
    ratings: 0.6,
    tags: ['Flowering', 'Low Light', 'Indoor'],
    shipping: {
      weight: 1,
      dimensions: {
        width: 0.7,
        height: 1.16,
        depth: 0.73,
      },
    },
    productDescription: {
      main: 'A perfect plant for indoor and outdoor spaces.',
      descOne: 'Comes in a beautiful decorative pot.',
      descTwo: 'Enhances indoor air quality.',
      descThree: 'Adapts easily to its surroundings.',
    },
    productDimensions: {
      height: '42 cm',
      weight: '2 kg',
      depth: '58 cm',
    },
  },
];
